### ISSUE TITLE
Add context to subtasks: ability to open AND create parent tasks (or see the hierarchy)

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#138]
When you see a subtask alone, it's very hard to know which bigger task it's part of. Having some kind of visual context would help a lot. Either : 
- another column containing the name of the root task
- a bread crum of the hierarchy appearing when you select the task and in the task window
- a tooltip with the name of the root task if you hover

Another thing is that it's hard to navigate in the group of subtask if you are not in the context of the task its self. Often, when you finish a task, you want to change something to the next task in the group or the parent task (change a tag, set a date, etc). Having some navigation button in the task window to go to the next/previous sibbling and to the parent would help with that.

**Comment by jakubbrindza** [comment]
Hi!
Thanks, your commentary makes sense and we realise this is a necessary feature.
Over the next week I will be redesigning the GTG editor and one of the features we plan to bring in is exactly this:
when you edit a (sub)task, there will be some navigation arrows in the header bar of the editor or at least a button "Open parent" which will navigate you to the parent. If the subtask has more than one parent (i.e. a hierarchy of parents), there will be a popover showing and you can choose which one of the parents you want to access and edit.

This is a solution for the editor we plan to implement.
I will think about how we could make the view in the browser clearer and easier to use!
Let me know what you think of the proposal I'm describing above, if that would be helpful :wink:

**Comment by sametmax** [comment]
I prefer inside navigation than opening a new windows (except if I explicitly ask for it with a middle click). But whatever you do it good, I'm already glad somedody is working on his free time so i can organize myself better and have more free time myself.

If you need me to test beta features, ping me, i'll be glad to. I know Python quite well, so I can report errors efficiently.

**Comment by nekohayo** [comment]
@jakubbrindza did you have an implementation in the works, or nothing at all? (just asking in case someone looking at this would like to work on it)

**Comment by nekohayo** [comment]
So, clarifying my thoughts on the matter... I too would like to be able to go "up" in a task's hierarchy or create a parent if there isn't one already, for simplicity and performance reasons:
* it happens quite often that I don't know if a task is just a subtask of another, and I don't want to enter/exit the workview (aka "Actionable" tasks) just to check because 1) it's incredibly computationally expensive 2) it takes you out of your current context 3) a parent task might not even be in the same tag as the child.
* why do I need to know that I'm in a subtask? because otherwise I have a tendency to cram a ton of redundant information into subtasks that may already be in a parent task, or a tendency to overload the title, or I don't know if I have properly defined the "next action" for a project, etc.

So **what I'm proposing is this**:

* In the task editor, a GtkButton (or a GtkMenuButton if there are multiple non-nested parents¹) that lets you either "Open parent" or "Create parent"
  * with a GtkTooltip that clarifies that it allows Opening or creating the/a "parent task/project" (because technically, I see a task with multiple subtasks as a "project" as per #245).
  * the button's label would tell me if the task I'm in is a "sub-task" or not.
* When marking a task as done (or not to be done, or deleted) in the task editor, after automatically closing this task window (which is the current behavior), we should automatically open the parent task's window.

This is up for grabs for anyone wanting to play with this feature request. I'm _thinking_ it's probably easy to implement thanks to liblarch, hence why I'm tagging this ticket "low-hanging-fruit", but maybe it's trickier than I imagine...

Theoretical notes and thoughts:
1. Aside from nesting/multi-levels, can a task actually be a child of multiple parents "on the same level" at once, @ploum ? I'm guessing "Yes in liblarch's theory" but "probably not in practice in GTG"? Does it make any sense to handle multiple equal parents for a task here?
1. Regarding "Should we show the whole nested chain hierarchy of parents if there are multiple levels?" I'm not sure that complexity is warranted (and you couldn't easily fit those long task names in breadcrubs, you'd need a vertical thingy, so you essentially end up creating a treeview, which... duplicates the task browser UI). I'm thinking that the user could simply "jump" repeatedly upwards across the hierarchy if needed, and otherwise they could use the task browser "All/open tasks" treeview to see the whole hierarchy...
1. I'm not sure how well GTG handles concurrent changes in children/parents while a task is open for editing. If it's unreliable, it might be desirable from a relability standpoint (also from a window management standpoint) to automatically close the parent/child when "jumping" to the other... but maybe I'm being techno-paranoid here.

**Comment by nekohayo** [comment]
Diego is pointing out that I'm a fool because there already is the "Open parent task" button in the git version, just not the "Create parent task" part. So one just needs to implement the "create" part, and refine the wording with my tooltip suggestions above etc, and then there will be much rejoicing!

**Comment by nekohayo** [comment]
This is now mostly implemented in commit 3baa1899 by @diegogangl ! However it uses the same button with no label,, with a tooltip that says _"Open the parent task (creating a parent if it doesn't have one)"_.

Ideally, I would recommend we use a button with a real shown label (rather than tooltip), setting the label text depending on if the task actually has a parent or not. Having a button labelled "Open parent" or "Create parent" depending on the situation would make it clear to the user that:
* a task has parents, it's like an invitation to "Read more..." for the user, if you see what I mean...
* a task doesn't have parents, so the user _knows_ that clicking the button would create the parent.

Right now, it's impossible to know if there are parents or not (especially with the static tooltip in the .ui file), so if you thought the task already had a parent but it doesn't, and you click the button, then you just created a parent... that you might not _actually_ have wanted to create.

The other reason why I'd recommend to have an explicitly visible button label is that the button's "^" symbol is not really obvious at first glance; to me that symbol usually means "move item upwards in a list" rather than "Go to parent" / "Create parent".

Also in the wishlist: if the task "externally" becomes a child of another (i.e. the task editor is open, but the user drags the task to be a child of another in the main window) then ideally GTG should be able to update the button label inside the task editor window to reflect that it now has a parent, and vice versa if it has been externally deparented; but that's a corner case that I can live with (or that we can split into another ticket for "someday") if it's overly complicated to implement.

**Comment by diegogangl** [comment]
I split the last bit about externally detecting parenting into its own ticket so we can implement it in the future. Also, this is done but I forgot to mention it in the commit >_>
