### ISSUE TITLE
Allow reorganising the tag pannel

### ISSUE THREAD

**Issue by sametmax** [getting-things-gnome/gtg#142]
Weither you prefer tags or search is a matter of preferences, but if you got a lot of them both, you'll want one of them to be on the top because you use it the most often. Right now you don't have that choice since you can't move the root categories of the tag pannel.

**Comment by izidormatusov** [comment]
You can drag'n'drop tags in tag pannel. You can put a tag below another tag and create semantically similar tags (e.g. Those are all work related tags/projects)

Currently tags are sorted by their name.

I'm closing this issue, feel free to reopen it if you have  specific ideas how to improve tag organization.

**Comment by tomspur** [comment]
Could the tasks be sorted according to their appearance in the task list? My tasks are sometimes sorted in a specific way and build upon each other, but instead of linking them together, I just write them down in the right order in the subtask.

Could that ordering be preserved or should one really properly link them in a row?

**Comment by izidormatusov** [comment]
@tomspur this bug was about organizing tags. Feel free to report a separate ticket. (Though implementing it won't be on the roadmap for GTG 0.4)

**Comment by sametmax** [comment]
I'm not asking to be able to sort tags (although this doesn't work either on my machine).

I'm asking to be able to move the 3 root nodes of the tag pannel : search, tags and "all tags". Right now, tags are at the bottom, and since search is always expended, I have to scroll to read my tags.

**Comment by izidormatusov** [comment]
Is the problem that those 3 root nodes are always there or because you have lots of saved searches that block your access to tags?

You should be able to collapse saved searches and GTG will remember your decision.

The upcoming changes in GTG:

 - to save search, you will need to press button, so they won't be automatically created.
 - if there are no saved searches, search "root node" will be hidden

**Comment by sametmax** [comment]
Yes, but no, gtg doesn't remember the collapsing decision (gtg 0.3.1 on ubuntu 14.04 + unity)

But even if it did, I still want to reclaim the space taken by the 2 first root node so I can see 2 tags instead.

**Comment by izidormatusov** [comment]
Why is it so important for you to move those 2 root nodes? What's the typical size of your window?

(I agree that we should fix collapsing those search tags if the user wants it)

**Comment by sametmax** [comment]
Nothing is "so important". It's a "nice to have". If you have a lot of tasks and tags, it's nice to be able to see as much as you can, that's all. Especially if you don't care about those 2 nodes, having them at the top is clutter.

**Comment by izidormatusov** [comment]
OK, I don't see those 2 special tags as a big deal and not planning to fix them.
