### ISSUE TITLE
Detect dark GTK theme changes at runtime to adjust background/highlight colors automatically

### ISSUE THREAD

**Issue by izidormatusov** [getting-things-gnome/gtg#150]
As described in [this blogpost](https://feaneron.wordpress.com/2015/06/22/introducing-gnome-to-do/), it would be really nice to have a support for black Gtk theme. (GEdit has the black theme as well).

**Comment by diegogangl** [comment]
This might not hang as low as we thought. Neither tree views nor text view tags can be styled with CSS.

**Comment by nekohayo** [comment]
I'm not 110% sure how it works these days anymore because somewhere in recent years GTK changed from having the notion of a theme's "dark variant" property/switch to having entirely separate dark themes (Adwaita and Adwaita-dark).

What does it look like when you use the Adwaita-dark theme (that you can set in gnome-tweak-tool)? At least in 0.3.x (which is GTK2) it looks 100% fine, both in the main window (treeviews) and the task editor windows, so I assumed it would also work that way in the GTK3 version?

**Comment by diegogangl** [comment]
Hmm you are right, I actually tested it and it's that big of a problem. The only things that look bad are the tasks with colored backgrounds and task titles. The first can be fixed by forcing a darker type color, the second can be fixed in the #235  branch

**Comment by nekohayo** [comment]
Tested out the current git version on Ubuntu 20.04 (Ubuntu being my benchmark for "will downstream break our UI" ;) with both the Yaru dark theme and Adwaita dark, and GTG works "fine".

* WORKING: Yellow tag text highlights inside the tag editor look fine, in the case of the highlights the text is black-on-yellow anyway. No problem there.
* MOSTLY WORKING: Task row colors in the main window, when the "Color the task rows based on the tag's assigned color" setting is turned on in the preferences, are already darkened when launching with a dark theme.
  * The case where it fails is if the user/system changes the theme while GTG is already running (which is something I do, I have a script that switches the system to the dark theme at nighttime). "Ideally" GTG should be able to connect to some sort of signal to be notified when the GTK theme changes at runtime, and adjust its colors accordingly? (presumably, if it can toggle the row colors on/off at runtime when you enable/disable the setting, it's probably just a matter of calling a toggle on+off of that thing once, if we want to be hacky about it)
* NOT WORKING: The only other case where it fails is the "urgency_color" plugin, since it has colors set in its configuration/properties dialog... ideally that plugin should have a fix to automatically compensate too.

Shouldn't be too hard to fix the "MOSTLY WORKING" and "NOT WORKING" issues mentioned above if someone is interested in playing with the code to have it support theme changes detection.

**Comment by johannesgunnar** [comment]
I also make gnome change theme during the evenings/night. I noticed this problem with background color on colored tasks being off. (latest flatpak version)
![darkthemeplustagcolors](https://user-images.githubusercontent.com/2924543/87211854-0f7b0b00-c30b-11ea-9dd8-5093dba322fb.png)

**Comment by Xanaxus** [comment]
hey so I just installed the application via popos app store as a flatpack but I haven't come across the option to change to dark theme is there a plugin for it?

**Comment by diegogangl** [comment]
@Xanaxus @johannesgunnar Hey guys, sorry for not responding. Master has a dark mode toggle now that sets up (almost) everything correctly. It's still missing some color changes in the text editor, that will have to wait until the taskview branch lands.

**Comment by nekohayo** [comment]
Interesting, though I have to ask, why would it have a dark mode switch/setting, vs just autodetecting system theme changes?

**Comment by diegogangl** [comment]
We need to have a switch somewhere so we can change colors that aren't affected by CSS. We could remove the switch from the GUI, but AFAIK Gnome doesn't have a way to set a global dark mode yet. You can change the theme using Tweaks but I don't think that's detectable via Gtk.

**Comment by nekohayo** [comment]
Spiritual successor: issue #608
