### ISSUE TITLE
Concat full name to tomboy note in task

### ISSUE THREAD

**Issue by ryseus** [getting-things-gnome/gtg#17]
Every time i edit/open task description its adding full name to tomboy note, if russian text stay before tomboy note
# 

System: Ubuntu 12.04 + latest updates on 25.04.2014
Installed Apps: 
- Gtg 0.3.1 + Tomboy/Gnote plugin 0.1.9 
- Tomboy 1.10.1

First and second picture in attachment are normal. After them pictures illustrates this bug.
# 

![normal _created](https://cloud.githubusercontent.com/assets/7404434/2799642/88f318c4-cc63-11e3-8b98-128ad48fc08a.png)
![normal _closed_and_opened once](https://cloud.githubusercontent.com/assets/7404434/2799644/8eb4b330-cc63-11e3-8f21-4a43acdf3811.png)
![bug _created](https://cloud.githubusercontent.com/assets/7404434/2799645/923f6f9a-cc63-11e3-8b03-1871a21e3018.png)
![bug _closed_and_opened_once](https://cloud.githubusercontent.com/assets/7404434/2799646/95859418-cc63-11e3-91d1-94ff583f1b9c.png)
![bug _closed_and_opened_twice](https://cloud.githubusercontent.com/assets/7404434/2799649/98bf3c10-cc63-11e3-840a-cb4d316b3c27.png)
![bug _closed_and_opened_third](https://cloud.githubusercontent.com/assets/7404434/2799650/9b4d451c-cc63-11e3-8ad6-f5fe2bc77e9c.png)

**Comment by nekohayo** [comment]
I'm working on reforming a community around this project and putting it back on its feet.

This bug report is very ancient, and it is difficult to guess if this problem still applies to the current development version.

Additionally, I'm not sure anyone can be expected to maintain something related to Tomboy in this day and age.

Due to our limited resources and the need to focus, I will close this ticket for now. If you still want to see this happen, please contribute code (or bring in someone who can) to the project for this purpose. Thanks!
