### ISSUE TITLE
Halting when syncing with Hamster and underscores in tags

### ISSUE THREAD

**Issue by robertwasik** [getting-things-gnome/gtg#198]
When "_" is present in tags, syncing with Hamser, starting Hamster from GTG window causes halting:

Traceback (most recent call last):
  File "/usr/share/gtg/GTG/plugins/hamster/hamster.py", line 344, in task_cb
    self.decide_start_or_stop_activity(task, widget)
  File "/usr/share/gtg/GTG/plugins/hamster/hamster.py", line 352, in decide_start_or_stop_activity
    self.sendTask(task)
  File "/usr/share/gtg/GTG/plugins/hamster/hamster.py", line 136, in sendTask
    fact += ",%s%s" % (description, tag_str)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 25-26: unexpected end of data

When underscores removed, everything works fine.

**Comment by nekohayo** [comment]
I'm working on putting this project back on its feet with the goal of getting a release out of the door.

This issue here is up for grabs for anyone wanting to see it happen. Please contribute code (or bring in someone who can) to the project for this purpose.

I do not use Hamster myself and orphaned code rarely gets better on its own. If nobody steps forward to maintain it, the code may get deactivated or dropped in the long run.

**Comment by flavin** [comment]
this is not reproducible in https://github.com/getting-things-gnome/gtg/pull/465 I think we can close this one
