### ISSUE TITLE
Number of tasks in title-bar doesn't decrease properly

### ISSUE THREAD

**Issue by ElchananHaas** [getting-things-gnome/gtg#203]
Linux mint 18-Cinnamon
GTG has the Notification Area plugin active
When you select a task and click "mark as done" the title-bar will not change from "5 active tasks - Getting Things Gnome" to "4 active tasks - Getting Things Gnome"
or more generally 
"N active tasks - Getting Things Gnome" to "N-1 active tasks - Getting Things Gnome"
If you switch in and out of work view mode, it will decrease. 
Picture attached, I just selected a task and marked it as done. 
![screenshot from 2016-12-20 19-51-07](https://cloud.githubusercontent.com/assets/7143767/21373618/5120ff82-c6ee-11e6-805f-8e1ed6292d16.png)

**Comment by atrosinenko** [comment]
This bug is reproducible with Lubuntu 17.04 daily and GTG version 0.3.1.

In fact, 
* it is reproducible both with "Mark as done" and "Mark as not to be done" in main UI and in separate task window opened by double click and with "Permanently remove this task" from that window as well
* when I somehow remove from list several task in a row (either as done, not-to-be-done or just remove), the counter starts to decrease, but it shows f.e. "3 active tasks" when only 2 are there (`9 active tasks`, mark as done, `9 active tasks` _in fact 8_, mark as done, `8 active tasks` _in fact 7_, and so on)

It looks like GTG updates its title-bar first and removes task from list after that, so the title bar corresponds to the task count as it was before the removal (old state) instead of after (current state).

**Comment by nekohayo** [comment]
Do you encounter this bug with the git version?

**Comment by diegogangl** [comment]
Master is using headerbars now, so this isn't as relevant anymore
