### ISSUE TITLE
Mint updates cause loss of preferences

### ISSUE THREAD

**Issue by sidestrand** [getting-things-gnome/gtg#207]
Many times when I install a Mint update I lose all my preferences and plugin preferences.  The side panel closes although my preference is to have it open and work view is not applied.  This definitely happens with kernel upgrades but also other updates.

**Comment by nekohayo** [comment]
I'm afraid this is not specific enough to be able to do much with it, see if it happens with the git version. In any case, system updates shouldn't affect the preferences of a user-level application, unless you somehow wipe your home directory (or store your data outside it, or something weird like that). Until proven otherwise with information and debug logs that demonstrate that something is resetting the settings, or that the settings are not saved at all, I don't think much can be done from our end on a bug tracker.
