### ISSUE TITLE
Days Remaining not updated in realtime

### ISSUE THREAD

**Issue by banjoman05494** [getting-things-gnome/gtg#214]
The Start and Due Dates show as actual dates until the even gets to within 7 days or so, then displays as "x days remaining".  Apparently this is only calculated when the app starts, and not again while the app is running.  In Ubuntu 16.04, users can suspend the session, and data for open apps is written to disk, then reloaded when the machine is powered up so you can continue where you left off.  I restart my machine only once a week or so, and so I have missed several event deadlines because the Start and Due dates still show as, e.g., "2 days remaining", even though the actual due date has passed.

It'd be good if GTG was changed to check and recalculate dates once or twice a day (via the system timer) rather than just at app start.

**Comment by nekohayo** [comment]
Yeah, I think it does that on startup and when you switch from one tags filtered view to another, or toggle workview on/off; at least that was the case with 0.3.x, I don't know if the git version behaves the same, please test it.

This issue here is up for grabs for anyone wanting to see it happen. Please contribute code (or bring in someone who can) to the project for this purpose. Otherwise, I doubt this will move forward soon.
