### ISSUE TITLE
Feature request: priority

### ISSUE THREAD

**Issue by HI-Lab1** [getting-things-gnome/gtg#232]
I hope sending this request here isn't off-topic. In that case, I apologise for it.
First of all thank you for this great software. I use GTG for professional work in the office work team and I'm asking many colleagues to use it. We all see an important lack of todo definition: **priorities**. It is true that it is possible to define the expiration date of the todo, but **urgency** and **priority** are two very different things. One thing can "expire" in two days, but be unimportant. Another thing expires in a month, but the amount of work it needs to be completed, and the great importance it has for the team, puts it among the priorities that I have to think about every day. And my colleagues and I would really like to see priority things first, regardless of their "expiration".
I think it is not a complicated thing (I hope) to implement in the software and I hope that you will put it as soon as possible.
Thank you very much and good job!

**Comment by nekohayo** [comment]
This is something I've sometimes wondered about, but haven't figured out a way to resolve this from a logical perspective: how would you have two different sorting systems on top of each other?

My guess is that the way the original GTG authors designed it, the feature you're looking for is already present in the app, in the form of the "now" (high priority, top of the list) and "someday" (bottom of the list, and hidden in workview mode) due dates. Since they're not attached to dates, but attached to "is this the top priority, or is this a research idea", this might work for you too. With these, I haven't personally felt the need much for a separate priority system over the years.

**Comment by nekohayo** [comment]
Another potential way I can imagine to deal with this for your usecase without complexifying the software, is to simply use a tag, like `@important` (and maybe set its color to red) and use that to filter your view to see only the top priority items? And they would already be sorted by "due date" within that tag's view.

**Comment by ploum** [comment]
There's no "priority" field on purpose. This was a core decision when starting GTG. Indeed, we have witnessed dozens of tasks lists from people using other software and the priority field is :

- taking more time to add a task. It also requires one more decision to add a task.
- In most case we witnessed, people only acts on "high" priority items, keeping "medium" and "low" priority as reminder (which is why we added "someday")
- people wanting to build an Eisenhower matrix can still use tags

**Comment by HI-Lab1** [comment]
Hi Jeff and Lionel, first of all thanks for your kind and quick response.

>  My guess is that the way the original GTG authors designed it, the feature you're looking for is already present in the app, in the form of the "now" (high priority, top of the list) and "someday" (bottom of the list, and hidden in workview mode) due dates. Since they're not attached to dates, but attached to "is this the top priority, or is this a research idea", this might work for you too. 

I've tried to use "now", "someday", "soon", but this replaces the expiration date, it is not superimposable.
Priority indicates the degree of importance of a given todo or task for an organization or company. I repeat: I can have a todo to complete by 10 January (in three days), but it could be something unimportant, one of those things that even if the deadline comes and remains unfulfilled, has no major consequences (low priority). But there may be something that needs to be finished by February 28th, but it requires a lot of work and is vital for my organization, so it has a very high priority, even if it expires in more than a month and a half. The latter todo I would like to see it at the top of the list and fiery red, although it expires on a date much later from the rest of the todo.

> Another potential way I can imagine to deal with this for your usecase without complexifying the software, is to simply use a tag, like @important (and maybe set its color to red) and use that to filter your view to see only the top priority items? And they would already be sorted by "due date" within that tag's view.

It's not the same thing Jeff. I'd thought about tags too, but the tags filter the todos, so I can only see the todos with "@high-priority", but I can't see the other todos with "@low-priority" and especially sort them by level of importance.

> we have witnessed dozens of tasks lists from people using other software and the priority field is taking more time to add a task. It also requires one more decision to add a task.

I do not agree Lionel, it's very simple: it is enough to leave the inclusion of the "priority" as **optional**, this avoids wasting time for people who do not need to define this feature in inserting todos...

> In most case we witnessed, people only acts on "high" priority items, keeping "medium" and "low" priority as reminder (which is why we added "someday")

That's not always the case. I manage complex organizations and complex projects. In time management there are time spaces that are not large enough for todo "high priority", where you can instead perform "medium" or "low". In addition, changing project conditions often lead to a reorganization of priorities.

> people wanting to build an Eisenhower matrix can still use tags

Of course, you're absolutely right! It's just the Eisenhower matrix we're talking about. In fact, in the presence of "priorities" todos can be sorted hierarchically first according to priority and within the priority by expiration date (which is currently impossible by managing the priorities with tags). If the priority is not set then only the expiration date will be used as the sort order of the todo lists.
However, the priorities could be indicated through an arbitrary numerical range, which would allow each one to be able to establish his own priority scale (in place of the usual "high", "medium" and "low"), while still maintaining the possibility of not prioritising and then allowing GTG to behave as it does today.

I really hope that I have explained well this important possible feature and I very much hope that my contribution will be useful to this beautiful piece of software.

**Comment by ploum** [comment]
When we started GTG more than 10 years ago, simplifying was our core principle. Having as few fields as possible was, since the start, the key of our UX.

We have, for years, refused to add other fields and I still believe we should keep it that way.

Most of the time, users who requested such fields came later saying that we were right and that not using them was, in fact, easier.
Some users were not satisfied and left for other todo software, which is fine. In fact, most todo software on the market have a priority field so it's not a big problem. GTG was created with the desire to explicitely not have that field.

We cannot please everyone and it's fine.

On the other hand, not being active anymore, I can only tell the historical view. It's an opensource project that could be forked if necessary.

**Comment by diegogangl** [comment]
> It's not the same thing Jeff. I'd thought about tags too, but the tags filter the todos, so I can only see the todos with "@high-priority", but I can't see the other todos with "@Low-priority" and especially sort them by level of importance.

This is a feature we should definitely work on for 0.5. It's tracked in #123 

I've been thinking about priorities recently too because I wanted to sort tasks in the workview so the ones I really need to get done show up first. I think this could be solved better with manual sorting, so you can drag tasks to the top. I think this combined with multiple tag selection should give you the same featureset as a dedicated priority field (and more too).

I've also been thinking headers would be useful to separate things more visually. Anyways, I think we can accomplish this by improving our features. Maybe we can check back later and see if we still a dedicated field.

**Comment by HI-Lab1** [comment]
It sounds like a good idea, let's wait to try it out on the field and see how it works.
Thank you very much Diego and thank you all!

**Comment by nekohayo** [comment]
Yeah, the ability to filter with multiple tags at once would make more sense in my opinion, so might as well just consider that to be the "proper" feature fix; updating tags here for clarity.
