### ISSUE TITLE
Tag editor redesign

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#276]
The tag editor needs some lovin'

- It saves data "live", it would be better if it had headerbar buttons to cancel and save
- The generate color function should have a button in this dialog. Let's just call it "Random Color"
- Make it look less GTK2-ish :)

**Comment by diegogangl** [comment]
Glade + inkscape mockup

![mockup_change_tags](https://user-images.githubusercontent.com/264829/80266268-5729b900-8671-11ea-8a66-71086d64a5bd.png)

**Comment by diegogangl** [comment]
Glade mockup

![glade_mock](https://user-images.githubusercontent.com/264829/80267702-c951cc00-8678-11ea-9647-483b91223bb7.png)

Pretty much done IMO. We should get this in master once we can support gresources, so we can use the template decorator

**Comment by nekohayo** [comment]
Eek, this "Actionable" on/off switch illustrates a problem I subconsciously had with the renaming of "Workview" to "Actionable": _Actionable_ isn't really a word that clearly states its meaning in this dialog. I also have a tendency to avoid GtkSwitch because it brings in [various usability problems](https://fortintam.com/blog/on-gtkswitch/) and in many cases a labelled checkbox widget is more appropriate.

If you want to retain the "Actionable" terminology, I would suggest to have a checkbox that says this:

- [x] Show tasks that have this tag in the "Actionable" view mode

or potentially clearer (but subject to string length changes as the user types the name:

- [x] Show "%(tag_name)s" tasks in the "Actionable" view mode"

or the reverse:

- [ ] Exclude tasks that have this tag from the "Actionable" view mode

...but then of course this breaks your grid alignment.

Personally, I think I might eventually like having both a "Workview" mode and an "Actionable" mode (issue #14), in which case you may then need to rename this switch back to the way it was because the workview is a subset of actionable tasks... unless it isn't and you somehow need two switches (I guess it depends if the eventual implementation of 14 is done as some sort of "two independent filters that the user can toggle in the UI on the fly" or not), but that's a detail for the future.

**Comment by diegogangl** [comment]
I checked out the HIG and when to use switches vs checkboxes isn't super clear-cut. TBH I don't mind it, I can re-arrange the layout to suit a checkbox np. Those labels look super-verbose though.

I'd go for something like  "Show in Actionable tab".

> Personally, I think I might eventually like having both a "Workview" mode and an "Actionable" mode (issue #14), in which case you may then need to rename this switch back to the way it was because the workview is a subset of actionable tasks... unless it isn't and you somehow need two switches (I guess it depends if the eventual implementation of 14 is done as some sort of "two independent filters that the user can toggle in the UI on the fly" or not), but that's a detail for the future.

This is going a bit out of scope but I don't think we need more tabs (or view modes).  We need better filtering and sorting options for them. Then if anyone needs a very specific combination of options they can save it (or maybe write a plugin). We can continue this in #14 but we can't do much about it yet, we need to move the main task list to listboxes and get the sorting/filtering code under control.

**Comment by nekohayo** [comment]
>  "Show in Actionable tab".

Ah yes, _('Show in "Actionable" tab') can work. Hadn't thought of calling it a "tab".

**Comment by nekohayo** [comment]
Given that your mockup's color picker button has a "Random" generator button, I think the only thing missing would be a "Delete" button, and maybe the Save button could be called "Apply" (or not)... but if we put the delete button in there, this opens up the way for getting rid of the tags' right-click popup menu and standalone tag editor dialog entirely, by combining EVERYTHING into a single "popover" widget.

So imagine your mockup, but embedded in a GtkPopover that shows then right-clicking a tag in the sidebar. That could make the redesign worthwhile, and save one click when editing a tag, though I'm not sure if popovers-on-popovers can work (for the color picker and the emblem/emoji picker), you might then need to either use some expander widgets, or maybe a _big_ three-columns popover design that fits everything at once...

**Comment by diegogangl** [comment]
Wouldn't the delete button conflict with the idea of the save button? 

We could include the color and emoji picker as subpopovers (like in the recurring tasks popup). I don't know if we can do that with emojis tho. The whole thing feels like too much for a popover tbh.

**Comment by nekohayo** [comment]
I'm late to the beastly #666 PR by @neui, and the new UI is pretty neat! If I may, here are some tiny nitpicks if you folks want to potentially polish it even more, but they're really not showstoppers by any stretch of the imagination:

* Labels would normally need a ":" to separate them from the property they control (at least, that was the case back in the HIG 2.0 days), so I would recommend "Name:", "Color:", "Icon:" (Actionable is a bit of a weird special case because technically it's not really a single word property... not sure what to do with that one)
* Since the icons are going to be shown at small sizes in a listview anyway, I'm not sure a big button to show them is necessary; therefore, wouldn't it make more sense to have them shown on a line just like the color setting? So basically a label that says "Icon:" (or "Emblem:" and then the clickable emoji picker button and then the linked trash button, so that it looks similar to the color property? The advantage/disadvantage though is that the window will be a little bit less wide naturally.

**Comment by Neui** [comment]
> * Labels would normally need a ":" to separate them from the property they control (at least, that was the case back in the HIG 2.0 days), so I would recommend "Name:", "Color:", "Icon:" (Actionable is a bit of a weird special case because technically it's not really a single word property... not sure what to do with that one)

I used the [HIG visual layout example](https://developer.gnome.org/hig/stable/visual-layout.html.en), which doesn't use the colon. I quickly went through the writing section, but didn't see anything about that.
![HIG example for labels, which doesn't include the colon](https://developer.gnome.org/hig/stable/figures/visual-alignment-spacing.svg)

**Comment by nekohayo** [comment]
Oh... I guess the rule changed, I still had the 2.x era rules memorized. Nevermind the colons then! Sorry for the false positive ;)
