### ISSUE TITLE
Saved searches has "Edit Tag..." and both "Delete tag" and "Delete" contextual menu items

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#283]
If you save a search, and then right-click it inside the sidebar, you have these options:

* Edit Tag... (should probably be named differently; it lets you change the "nickname" of the search and assign a color or icon, which is interesting, but the UI was clearly for tags...)
* Generate Color
* Delete Tag (doesn't do anything)
* Delete

"Delete Tag" should be removed and "Delete" should probably become "Delete saved search".

**Comment by jscn** [comment]
As mentioned in the PR, the Edit Tag... option is pretty misleading and just changing the name of it doesn't help much since you can't actually edit the search terms in the window that it opens. 

Probably it should be removed entirely, or the window should be replaced with one that is specifically for editing the saved search.
