### ISSUE TITLE
Port to lxml and improve xml-related code

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#285]
[Lxml](https://lxml.de/) is apparently *40 times* faster than minidom and has a nicer API. We should definitely switch to it. We can also drop all the code to prettify the XML, since lxml takes care of that.

And once we are sticking our hands in the parser/serialize code, we should also do a deep refactor and improve that code. The whole thing is full of "fixme" comments and _that can't be good..._

**Comment by nekohayo** [comment]
40 times faster? Great Scott! I'll very much love to see benchmarks before/after. If true, I cannot argue with such a migration. And that would make me happy because:

1. I had some suspicion about claims that XML was fundamentally flawed as a format from a performance standpoint, was suspecting we were rather just "spamming it in silly ways"; but if we can have a faster XML engine then that's even better, we can have our cake and eat it too. We should probably still have provisions in the code to avoid spamming it "for no good reason" though.
2. I like having a human-readable (and editable) format like XML instead of SQLite; it happened a couple of times that I went into the GTG tasks XML file with a text editor to search (and replace) some things faster than the GTG UI allowed, or to troubleshoot.
