### ISSUE TITLE
New task windows are placed far off

### ISSUE THREAD

**Issue by cars10w** [getting-things-gnome/gtg#287]
Hi,

when windows for tasks are opened (either by creating a new one or by editing an existing one) they appear on my secondary desktop-screen. Basically at position 0,0 of the whole desktop.

I would expect it to pop up on the same screen as GTG itself is running, vertically/horizontally centered within the main-window. Also they are placed in an overlapping manner if you open multiple task-windows.

As it is right now task-windows are placed "too far away" from my main focus/workflow for it to be effective.

Thanks a lot!

**Comment by nekohayo** [comment]
Are you running a Wayland-based desktop, or a X11/Xorg one? What window manager? Which version of GTG?

I remember such things being in the jurisdiction of the window manager rather than the applications, who can't (as far as I know) have knowledge of what other windows are present on the desktop (so it could only manage its own, but how would it know to position them in a tiling manner automatically?); particularly, this was a problem on GNOME with Metacity/Mutter for a long time until they fixed it and made the windows appear centered instead of at (0, 0), and then it might all have reset and the problem made a comeback with Wayland, I'm not sure...

**Comment by diegogangl** [comment]
Seems we were not doing any positioning when we windows didn't have a previous position saved. Editor windows (not opened before) now appear under the cursor.

**Comment by cars10w** [comment]
Yes,  https://github.com/getting-things-gnome/gtg/commit/565e868a2a044af4fb29e97eca493839d8db36b8 fixed it. Thanks a lot!
