### ISSUE TITLE
Warnings and tracebacks when trying to close task editors one after another with shortcut keys

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#290]
Interestingly, with the latest changes in commit 54405556c that were meant to fix issue #263, GTG now emits a warning everytime you close a task editor window:

```
WARNING - application:close_task:467 - Tried to close tid d318eaed-03de-42dd-adfd-66a44bf2261c but it is not open

Traceback (most recent call last):
  File "GTG/gtk/application.py", line 290, in close_focused_task
    tid = self.get_active_editor().task.get_id()
AttributeError: 'NoneType' object has no attribute 'task'

WARNING - application:close_task:467 - Tried to close tid f53f937f-72a1-450a-b2ae-f4038a401ac3 but it is not open
```

The traceback happens if you repeatedly hit Esc/Ctrl+W, as the windows get unfocused in favor of the main window (a side-effect of them being utility windows maybe). Wondering if there should be some focusing mechanism that focuses the next non-minimized utility window on closing one task window, or if that's too much of a hack...

**Comment by diegogangl** [comment]
In the end I couldn't make this focus the next window properly. I mean it _usually_ worked, but there was some kind of race problem between what the window manager wants to do and GTG. 

One solution I tried was closing the last opened window even if it wasn't focused. But I'm not sure about it usability-wise, since the same action would be mysteriously doing two different things depending on which window has focus.
