### ISSUE TITLE
Mastodon account

### ISSUE THREAD

**Issue by ploum** [getting-things-gnome/gtg#294]
I've seen the shiny new Twitter account. I think GTG should also have a Mastodon account.
I've spotted two FLOSS specific instances :
https://floss.social/about (where GNOME masto account is) and https://fosstodon.org.

It can also be synced thanks to https://crossposter.masto.donte.com.br/

**Comment by nekohayo** [comment]
Thank you for doing the research and proposal with the specific suggestions on where to have it. That solves one of my issues with Mastodon, which is "which $%%&ing instance am I supposed to pick?"

The other issues I have is needing to log on yet-another website, but that's OK. The biggest apprehension I had is I heard it (at least the web UI, I guess) doesn't have such a thing as scheduled postings (which Twitter's Tweetdeck has), and I don't know if it has such a thing as team permissions. Do you know if those exist in the main implementation?

**Comment by ploum** [comment]
Not that I'm aware of.
But, in the meantime, you could simply use the bridge to crosspost with twitter. Remove a lot of burden.

**Comment by ploum** [comment]
asked Mastodon : https://mamot.fr/@ploum/104072741918695113

**Comment by ploum** [comment]
For the record, a lot of GNOME developers are also on Mastodon. You should quickly feel at home ;-)

**Comment by ploum** [comment]
For scheduling: https://fedilab.app/

**Comment by nekohayo** [comment]
I have now created https://fosstodon.org/@GettingThingsGNOME ; as it does not handle teams, I guess I will be the single point of failure for this...

**Comment by ploum** [comment]
Why not "gtg" ?

I just learned that fosstodon is blocked by the bridge so floss.social might be a better choice now that it's easy to change (no followers to migrate).

**Comment by nekohayo** [comment]
> Why not "gtg" ?

Dunno, thought it was better to be explicit and to avoid potential clashes/confusion with whoever else might use that sort of nickname

> I just learned that fosstodon is blocked by the bridge so floss.social might be a better choice now that it's easy to change (no followers to migrate).

Oh f*** me, how do I do that then? I have no idea.

For what it's worth, so far I'm finding the (decentralization) experience a bit painful, _particularly_ compared to Twitter's Tweetdeck:
* Not being able to configure the columns / add more columns in the "advanced" official web UI (like you would in Tweetdeck)
* No search columns to be able to monitor various topics
* No visible toot scheduling feature (I saw https://github.com/tootsuite/mastodon/issues/340 where it is supposedly implemented but couldn't find anything in the default UI for this)
* No teams and no multi-account support

...all papercuts that make me feel terribly improductive/handicapped in it. I'd like to see these features as part of the default/official web interface offering, I'm not going to go chasing down a gazillion clients to install (I particularly _don't_ want to use mobile apps) that may have XYZ feature or bugs and may or may not be maintained in a few years... I guess I'm just old :)

**Comment by ploum** [comment]
On mer, 29 avr, 2020 at 09:24, Jeff <notifications@github.com> wrote:
>> Why not "gtg" ?
>> 
> Dunno, thought it was better to be explicit and to avoid potential 
> clashes/confusion with whoever else might use that sort of nickname
> 

damn hard to type. I would go for the simpler.
>> I just learned that fosstodon is blocked by the bridge so 
>> floss.social might be a better choice now that it's easy to change 
>> (no followers to migrate).
>> 
> Oh f*** me, how do I do that then? I have no idea.
> 

maybe we could just not care. There's another bridge.
> For what it's worth, so far I'm finding the (decentralization) 
> experience a bit painful, /particularly/ compared to Twitter's 
> Tweetdeck:
> 
> Not being able to configure the columns / add more columns in the 
> "advanced" official web UI (like you would in Tweetdeck) No search 
> columns to be able to monitor various topics No visible toot 
> scheduling feature (I saw tootsuite/mastodon#340 
> <https://github.com/tootsuite/mastodon/issues/340> where it is 
> supposedly implemented but couldn't find anything in the default UI 
> for this) No teams and no multi-account support
> ...all papercuts that make me feel terribly improductive/handicapped 
> in it. I'd like to see these features as part of the default/official 
> web interface offering, I'm not going to go chasing down a gazillion 
> clients to install (I particularly /don't/ want to use mobile apps) 
> that may have XYZ feature or bugs and may or may not be maintained in 
> a few years... I guess I'm just old :)
> 

It's opensource, you cant contribute to it. Personally, I don't care 
much about those interface. In fact, I even use the "simple" version of 
Mastodon. You may contribute to an external Mastodon client ;-)

**Comment by nekohayo** [comment]
So, regarding renaming the account username: I can't find a way to do that in the web UI/account settings...

**Comment by ploum** [comment]
You can't, afaik. it should be a new one.

**Comment by nekohayo** [comment]
If I understand correctly then, I have to create a whole new account as gtg@floss.social (and not fosstodon) and hope that instance doesn't get blocked/delisted/deprecated in the future, and then set a redirect, and ideally also tell people to migrate their subscription to the new account (because I'm not going to keep the old one around, no sir)...? This feels like the 90's. I have to admit I am rapidly losing patience for this kind of hoop jumping particularly if it relies on me being the "single point of failure" for that account. I don't like a piece of infrastructure being tied to me. I am pondering whether it is truly worth it.

**Comment by ploum** [comment]
Yeah, that's the major-huge problem of Mastodon. I've even written 
about it but never published because I felt it was not worth the 
effort. The main problem is not so much technical than philosophical: 
Mastodon is full of cuddlebear-nazi who want love, resepect for 
everyone *and* kill nazis.

This leads to an absurd situation but, I believe, this is only a tiny 
minority that migrated early to Mastodon because Twitter was full of 
nazis. Over the years, the situation is becoming less absurd because 
more and more people join who don't care about this shit.

**Comment by nekohayo** [comment]
Hmm, where did you read that fosstodon was blocked from the federation, vs floss.social? I can't seem to find something about this. But then I can't seem to find a sensible, understandable summary list of the best instances to be on without going insane, either.

I'm going through the extra mile to be researching topics such as:

* https://carlchenet.com/the-importance-of-choosing-the-correct-mastodon-instance/
* https://github.com/tootsuite/mastodon/issues/5645 which points to https://github.com/tootsuite/mastodon/issues/177 but that's not really the same thing
* https://github.com/tootsuite/mastodon/issues/109 from previously finding https://mashable.com/2017/04/06/you-cant-delete-your-mastodon-account/
* then I stumble upon https://olimex.wordpress.com/2020/03/05/bye-bye-mastodon-our-account-on-fosstodon-org-was-deleted-yesterday/ and find a new worry entering my mind.

And it is _not fun_.
So far the time spent researching how to sustainably deal with the complexity, papercuts and caveats is just making me unhappy and unproductive, and I'd very much rather be focusing on other aspects of GTG (and my life).

I see four ways forward (a.k.a. pointing out the mammoth in the room):

- A: Keep using the existing username and instance, if it's not a dead end? a.k.a. "the path of least resistance"
- B: Create a new "gtg" account on floss.social and delete the old account (if at all possible), and maybe screw "doing things properly". If I can get some assurance that this is the be-all-end-all "correct" instance to be on. I don't want to have to change instances again.
- C (also compatible with A and B): I hand over the account to someone else who is trustworthy, cares enough and has the patience for this kind of stuff... assuming I _can_ easily change the email address associated with the account and there aren't more such surprises. But then this doesn't solve "bus_factor==1". It could go rogue just like the old website.
- D (if "none of the above" are good enough): Give up on this experiment and delete the account entirely (if even possible) instead of advertising a half-hearted attempt like "scenario A" would be, and just focus on Twitter (and probably no other social networks) because it doesn't require a Ph.D from a German university to manage.

I hold no grudge towards Mastodon or anything like that, it's just that it is putting me before a choice where the costs—in terms of life complexity—are making it an increasingly hard sell for me personally every time I stumble on "Oh it doesn't do that?" and "Oh so doing this is not the 'correct' way?"…

**Comment by ploum** [comment]
I would say A. I'm not worried too much about using Fosstodon (official Debian account migrated away but some other projects still use it). I just find a bit sad to not have gtg (which is the de-facto name for the project, even the debian package has it) but, it's pure bicycle shedding so just forget about it and use https://moa.party for the bridge

**Comment by nekohayo** [comment]
I guess I'll consider this fixed / "good-enough", since we never know if, due to https://discourse.gnome.org/t/official-proposal-how-we-define-gnome-software/3371/15, we might (or might not) be forced to change the whole project name someday _anyway_ (which is a whole other bikeshed to paint, and I don't have spontaneous ideas of alternative names nor do we have time for this branding exercise when we're simply trying to revive the project first and foremost anyway)
