### ISSUE TITLE
Implement undo & redo in the "task editor" window

### ISSUE THREAD

**Issue by XioNoX** [getting-things-gnome/gtg#296]
In most (all?) text editors hitting ctrl+z undo the last action, like word or character typed/removed, etc...

This has never worked in GTG, old or current master version. So for example removing a task's content by mistake needs to be re-typed.

**Comment by nekohayo** [comment]
Indeed I don't think I recall anyone ever having implemented the notion of undo/redo in GTG. I suspect this is non-trivial, so marking as "patch-or-wont-happen".

For anyone willing to work on implementing it:

* As a starting point for inspiration, you might want to look at Pitivi's undo-redo implementation (since it's also Python + GTK): https://gitlab.gnome.org/GNOME/pitivi/-/tree/master/pitivi/undo ; I'm not entirely sure how reliable Pitivi's implementation is, but in theory GTG's would be simpler since it would only be for the task editor, so a much simpler scope.
* Someone implementing this would need to first write tests for GTG's test suite (so, test-driven development), as extensively as possible; I've seen enough apps with buggy undo/redo in my life, that I would like some assurance that if it gets implemented, it is implemented in a reliable way for users.

**Comment by diegogangl** [comment]
The editor is a nice start, but it'd be better to have undo through the app. As for how complicated it will be, it's hard to tell. The code the text view is in `taskview.py` and it's quite a beast.
Also, if this is to be TDD we need to unbreak the tests first.

**Comment by nekohayo** [comment]
I'm not sure why we would need undo/redo in the main window / outside the task view, because the "Mark as done" and "Dismiss"  actions have their opposites ("Mark as not done" and "Mark this task as to be done") that essentially _are_ undo. That feature still seems to work in the git version, although it is not as visually clear compared to 0.3.x, as detailed in issue #298.

**Comment by diegogangl** [comment]
- Applying modify tags (Ctrl+T)
- Editing a tag
- Deleting a tag/task should give you the chance to undo (as long as they are in memory)

**Comment by nekohayo** [comment]
I'm not sure it's worth the complications:
* Applying and editing tags are not really destructive actions (as a user, you can always overwrite a change you just made to tags)
* Deleting a tag is protected by a confirmation dialog. And if you somehow got past that and say "ooops, even if the software tried to stop me, I changed my mind later on" then... you can always batch-retag the issues you want, effectively recreating the tag...
* Deleting a task is also protected by a confirmation dialog (warning that it is permanent), and deletion not being undoable is why "dismiss" exists as a softer version of "delete".

So yes in theory those could all be undoable actions, but I feel like this might needlessly and significantly complicate both the backend and the UI, vs simply supporting undo-redo of the _contents_ of a task _at the "task editor dialog" level_ to solve the essence of what Arzhel requested. Just my 2¢ ;)

**Comment by diegogangl** [comment]
Yeah, it would make things more complicated but I think it would also make the user experience much smoother. Implementing undo for the task editor is already enough of a task, anyways :)

**Comment by diegogangl** [comment]
This was implemented for all textviews in Gtk4, so we should get it for free when we update:
https://gitlab.gnome.org/GNOME/gtk/commit/15b3c0f563d73787c574d1d03d627fbc46db59c4

Let's wait until we port to Gtk4 and buy Christian a beer
