### ISSUE TITLE
Translation files are not used by the "debug.sh" (gtg.sh) dev environment launch script

### ISSUE THREAD

**Issue by iootaa** [getting-things-gnome/gtg#304]
Hi there,

I'm running gtg 0.4 from the git repository and the user interface is not translated :
the default tasks are displayed in french, but the whole interface is still in english

I checked the file `fr.po` and everything looks correctly translated (no fuzzy string)

**Comment by nekohayo** [comment]
Good catch... I hadn't even realized this as I set up my dev machines in English lately.
My guess is that this is due to two things:
* Don't we need to compile translations into the ".mo" binary form (using `scripts/generate_mofile.sh`  I suspect) before the application is able to use them?
* They probably need to either be installed systemwide, OR _maybe_ there is a way for the GTG git launch script (`scripts/debug.sh`) to set some sort of custom environment variable to load the local .mo files instead of looking systemwide? But I don't know how to do that (it's been so long...), is this even possible?

For what it's worth, I had a very quick look at Pitivi by doing this:

```
git grep "po/" | grep -v svg
git grep "/po" | grep -v svg
git grep "LANG" | grep -v svg
```

...but nothing clearly jumps at me as being something to tell the locally-run app to look for the po/ directory. No mention of this in https://gitlab.gnome.org/GNOME/pitivi/-/blob/master/bin/pitivi-env either.

If this is actually possible, someone please tell us how this can be done (or provide a patch :)

**Comment by nekohayo** [comment]
I think I found a potential solution for this. As I suspected, you would need the app to "know" that it's being run in the git/dev version, and to guess which translation file to load, and to load it explicitly. Searching for "gettext translations run path variable", I found this thread, which has some sample code: https://stackoverflow.com/questions/10094335/how-to-bind-a-text-domain-to-a-local-folder-for-gettext-under-gtk3

Someone on #gnome-hackers on IRC also mentioned https://github.com/pithos/pithos/blob/master/bin/pithos.in as an example; it seems that one uses a different (simpler?) approach.

Otherwise, with the first approach, I can see two ways to handle this:
* adding a commandline parameter to specify to GTG which translation file to use (the easy way, in terms of implementation, but might feel a bit like a hack), or...
* the app autodetects the user's locale (or gets it from the "LANG" environment variable?) and automatically sets the correct domain/path/etc. when run in the git version (a.k.a. the nicer but more complicated way, and you may still need to have an override mechanism to set a different language than the user's system language, or to force the app's untranslated a.k.a. "C" version)

It looks do-able "reasonably" easily, but I don't have the time/energy to tackle that myself, so I'll mark it as a "low-hanging-fruit" issue to ask the public to contribute a fix for this. And alongside the code improvement, the implementer should write a little bit of explanation on how to use this (probably as a markdown file in docs/contributors/

**Comment by leio** [comment]
This is a next step in my meson work, so I'll get this working soon.
