### ISSUE TITLE
Document the process to contribute to translation and localization

### ISSUE THREAD

**Issue by iootaa** [getting-things-gnome/gtg#305]
Hi,

AFAIK there is no reference to the translation process neither in the git repository or on https://wiki.gnome.org/Apps/GTG

Someone planning to help translate gtg should find a brief Howto somewhere, or at least a reference of https://translations.launchpad.net/gtg

Cheers

**Comment by nekohayo** [comment]
I guess a question here is if we still want the project to be using LaunchPad for translations, or to rely only on people contributing updated versions of the translation files or being part of the GNOME translation team... In the past, I've sometimes found the quality of translations coming from LaunchPad to be a bit subpar, especially when people are just translating "blindly" without testing the app with their changes or looking at the surrounding code when needed...

**Comment by nekohayo** [comment]
In a way, this is kinda blocked/dependent on whether #234 happens or not, because if it migrates to GNOME then the process is different (relying on the translation teams)

**Comment by nekohayo** [comment]
In https://github.com/nekohayo/gtg/ I have a branch called "translations" where I've done a ton of work to improve the translatable strings to prepare the ground for translators. Hoping to get a review from @leio (if he has time and energy) and/or @diegogangl and to merge it ASAP this week.

Then, one thing I've been wondering, is what do we do to get the upcoming 0.4 translated "efficiently" as we're not yet hosted on GNOME infrastructure to benefit directly from the GNOME translation teams.
* Should we upload an updated POT to LaunchPad and make use of LaunchPad translators (if those still exist) to get some work done closer to completion for the release?
* Should we instead ask GNOME translators (through the upcoming prerelease blog post) to state in a comment on a meta ticket (i.e. we create a "Update translations for 0.4" ticket where they can comment) that they're they're working on a particular translation (to avoid duplicate work if possible) and send to send merge requests or email resulting .po files?
* Should we block on a migration to GNOME's gitlab (I would much rather not have that scenario, because that would mean _yet another_ yak to shave)?

**Comment by leio** [comment]
imho lets just start making releases and the translations will come over time as we get it figured out. If we do indeed go to GNOME gitlab and infrastructure and can head towards damned-lies, I think we could just as well wait for that to get done and actually have a program that's usable in English at least again, with py2 gone from distros.
For those really interested, we can try to routinely push gtg-update-po results until we are on some translation infrastructure (that will likely shun doing this step ourselves) and the translations updates can be sent in with pull/merge requests.

**Comment by nekohayo** [comment]
Created issue #358 so that translators have something to "take the lock/bâton" for their language while working on the translation.
