### ISSUE TITLE
Port sidebar to listbox (plus improvements)

### ISSUE THREAD

**Issue by diegogangl** [getting-things-gnome/gtg#308]
This is an issue to track improvements to the sidebar, along with porting to listbox.

- Use listboxes, so we can actually design the row layout
- Double clicking on a name should let you rename a tag from the sidebar without going through the dialog
- Saved searches should be hidden if there are no saved searches
- Likewise, tasks without tags should also be hidden if empty
- Task counts should update following the active tab
- Use emojis instead of custom icons (following #85)
- Move color to the right 
- Since color is on the right we need a placeholder icon/emoji to avoid shifting the tag name when it has no icon. It could be a empty square outline too.
- Use nautilus sidebar CSS to make it look more like it. This has to be tested, it might not be a good idea for dark / third party themes
- Maybe there should be an "edit button" for the selected tag? (so it's more discoverable and not only available through RMB)
- It should be possible to re-order tags manually by dragging and dropping. We could add some button on the context menu/popup to organize them by name/task count. These would reset the manual order.

Crappy inkscape mockup inbound:

![mock_gtg_sidebar](https://user-images.githubusercontent.com/264829/81488242-ac062b80-923c-11ea-9b11-680b3b60f800.png)

**Comment by nekohayo** [comment]
> This is an issue to track improvements to the sidebar, along with porting to listbox.
> 
>     * Use listboxes, so we can actually design the row layout

I see you are valiantly volunteering to add a second (Listbox) supported type of widget to libLarch :smiley:

I agree on everything you list so far, except potentially a few items below:

>     * Double clicking on a name should let you rename a tag from the sidebar without going through the dialog

Either that, or "double-clicking or long-press brings up the editing dialog embedded in a GtkPopover"?

I'm not sure relying on double-clicking only for renaming would be good for discoverability... which resurfaces in your other question:

>     * Maybe there should be an "edit button" for the selected tag? (so it's more discoverable and not only available through RMB)

My suggestion to map double-click + longpress to "Edit" solves that concern. Otherwise I could also say that you ought to have an "add" and "delete" button in there, so you would end up with a non-scrollable "inline-toolbar" at the bottom of the sidebar for "Add / Edit / Delete"...

Heck, you could even map ANYTHING that isn't single-left-click to it: double-click, long-press _and_ right-click; the popover (which would then need to have the "Delete" functionality) would thus literally replace the contextual menu. And since it'd be mapped to right-click, renaming could then take a single click: "right-click, the name is preselected so you can overwrite it, hit Enter to save & apply & dismiss the popover" (compared to your approach requiring the same but with two clicks + Enter, or the existing approach that still requires two clicks + Enter)


>     * Move color to the right
> 
>     * Since color is on the right we need a placeholder icon/emoji to avoid shifting the tag name when it has no icon. It could be a empty square outline too.

I don't see why you would want to do that. To me the user has the choice between either the emoji or the colored square/circle as fallback. By separating the two, you're doubling the visual clutter

>     * Use nautilus sidebar CSS to make it look more like it. This has to be tested, it might not be a good idea for dark / third party themes

Maybe it could be made conditional to happen only when running an approved (routinely tested) theme like Adwaita and Adwaita-dark? Dunno, sounds a bit like a minefield to me.

**Comment by diegogangl** [comment]
> I don't see why you would want to do that. To me the user has the choice between either the emoji or the colored square/circle as fallback. By separating the two, you're doubling the visual clutter

Because if you select an icon it replaces the color square and now you don't know what color the tag is using.


> Maybe it could be made conditional to happen only when running an approved (routinely tested) theme like Adwaita and Adwaita-dark? Dunno, sounds a bit like a minefield to me.

Yeah, it's mostly a small aesthetic and UX detail. If it doesn't work out we can do without it.

> Heck, you could even map ANYTHING that isn't single-left-click to it: double-click, long-press and right-click and the keyboard's "contextual menu" key (usually on the left of the right "Ctrl" key; though it seems Gtk already automatically handles it as a right-click). The popover (which would then need to have the "Delete" functionality) would thus literally replace the contextual menu. And since it'd be mapped to right-click, renaming could then take a single click: "right-click, the name is preselected so you can overwrite it, hit Enter to save & apply & dismiss the popover" (compared to your approach requiring the same but with two clicks + Enter, or the existing approach that still requires two clicks + Enter)

I'm kind of liking this idea! Though the dialog might be a bit too much for a popover. But we could have a popover with a name field to quickly correct misspellings and then a button to open the whole dialog. As well as the delete button.

Also, can we add tags like that? It seems like we need at least one task for a tag to exist

**Comment by nekohayo** [comment]
> Because if you select an icon it replaces the color square and now you don't know what color the tag is using.

This points to the good old _"Enabled colored backgrounds in the task list"_ feature for synesthetes, which _only_ controls whether you additionally see the color on as the background of the tasks in the task list's treeview _in addition_ to "the emblem/emoji OR colored square".

...but the primary visual identification method is always supposed to be the emblem/emoji (in other words, there is no such thing as having both the emblem and the colored square in the tasks list), otherwise why would you have set that emblem/emoji at all? If you want the color to show as an emblem, then just set the color and don't set an emblem icon/emoji.

This is actually why I remembered it as being, in practice, "either the emblem OR the color", but strictly technically speaking both can actually be set—just that only one of them gets shown in the icons column of the task list at any given time.

**Comment by diegogangl** [comment]
Well, that makes sense :thinking:

**Comment by nekohayo** [comment]
The only trick thing I can imagine is that maybe mixing emojis AND "some arbitrary colored square" in the same "column" would be technically impossible with TreeView (?), but hopefully listbox would open up the possibility for that to work?

**Comment by diegogangl** [comment]
Something I've been thinking about this: we might want tags to be under a collapsible header of their own too. We might want to make it possible for plugins to define their own filtering systems and add items to the sidebar in the future. With the tags under a header, we would have a cleaner division and the possibility of hiding them, but still have filtering from plugins.
