### ISSUE TITLE
Improve the guidance for installation

### ISSUE THREAD

**Issue by nagytech** [getting-things-gnome/gtg#316]
I recently searched the web for 'gtd ubuntu' and found this project.  It's been about 10-20 minutes now and I still do not have the software installed.  So, here are my painpoints that I'm hoping we can resolve.  I'm happy to help, but just wanted to document the issues before I go changing the documentation.

### 1. README.md
After a quick scan of the README.md, it's apparent that the only way to install is to build from source.  But, on deeper inspection, I can see there is a snippet below that leads the user to some instructions for a package based install.  However, the text is very easy to gloss over.
> See our website for the list of features and information intended for users (including how to install the stable release with pre-built packages).

Suggestion: It would be good to have a bold heading of 'Installation Options' to quickly sumarize the various ways of installing.

### 2. Landing page
After clicking the link in the above page, I had to scroll and scan a bit to find the "Downloading and installing GTG" link near the bottom.

### 3. Installation page
Reading carefully through the "Install" page, I found no obvious set of instructions for how to install the package.  And, after searching the web for "flatpak gtg", I just landed back where I was.  (Also, Flatpak is spelt incorrectly as 'Flatpack' in one location and I ended up searching the wrong thing)

Suggestion: On this install page, I think some `<code>` block, or reference to the flatpak package would help.

Also, If there's anything I can do to help get the flatpak packages up and running, please let me know.

![image](https://user-images.githubusercontent.com/8542033/82428037-4122e300-9acd-11ea-8959-156ce1aab6d6.png)

**Comment by nekohayo** [comment]
Yes, well that's because you've "unluckily" encountered GTG in a transitional period where the project is resurrecting (#210), the whole documentation has [just been rewritten](https://fortintam.com/blog/improving-developer-experience-and-attracting-open-source-project-contributors/) and the flatpak packages don't yet exist (#233)... so it's almost "normal" that you've been running in circles a bit (particularly as there is no 0.4 release yet, so in practice the only way currently _is_ to test & run the development version until that happens, unless you have a very old 0.3.1 package sitting around).

As you point out the "README.md" of the github repository (which is really meant as a place for development) points out at the top of the file that this is meant as the development grounds and that users should refer to the wiki page:

> You are currently reading the index of the information intended for **new contributors** (beta testers, developers, packagers, etc.), found in the project's main software development and management hub.
> See our website for the list of features and information intended for **users** (including how to install the stable release with pre-built packages

Do you have suggestions on how to make that clearer without the README ending up duplicating the wiki? "Installation Options" doesn't sound entirely accurate to me because that's not really what the distinction is about,  and if possible I'd like to avoid overloading the contents too (which I felt were already at the limit of being "long").

The (wiki) landing page would benefit from a better layout and navigation, but I ran out of time and energy to research & do that (one would need to go through https://wiki.gnome.org/Apps and study the best layouts and how their wiki code works). Technically anyone with a GNOME account can edit the page and improve that directly, otherwise I'd like some guidance if I'm to do it myself :)

As for the installation page... yeah there's no officially published flatpak yet, so again that's why there are some holes in that documentation. Hopefully this will be resolved soon as @diegogangl has already been working on flatpak packages on his end...

**Comment by tim-win** [comment]
I'd recommend adding a header to all three areas of documentation: the github README, the Landing Page main section, and the Landing Page Installation section. It would ideally state the same information you posted here: GTG is in a transition period, and the only way to install at present is via source.

**Comment by nekohayo** [comment]
At the same time, with @leio's Meson build work being on the verge of merging, and @diegogangl's flatpak packages being near ready (or ready? I'm kind of losing track of what's missing there), it might be quicker/less wasteful to "just get the packages readied officially" so that the documentation is no longer lying :)

**Comment by nagytech** [comment]
@nekohayo 

> Yes, well that's because you've "unluckily" encountered GTG in a transitional period where the project is resurrecting (#210), the whole documentation has just been rewritten and the flatpak packages don't yet exist (#233)... so it's almost "normal" that you've been running in circles a bit 

Thanks, it's good to know it's not just me.  

> As you point out the "README.md" of the github repository (which is really meant as a place for development) points out at the top of the file that this is meant as the development grounds and that users should refer to the wiki page:

I see where you're coming from, duplicating documentation is certainly difficult to manage.  However, I feel like most projects I encounter on GitHub these days have some Install or Getting Started section that's hard to miss.  

As an example, we have microk8s quickstart in the README here (https://github.com/ubuntu/microk8s#quickstart) but also in the Wiki here (https://microk8s.io/docs).  Perhaps that's a bad example to use, because of the scope of the project.  It's likely that there's entire teams at Canonical dedicated to documentation.  

If the packages were ready, I'm sure my attempt to find the flatpak install would have been fine.  But, I'll check through how the Gnome wiki is put together and if there's anything that can help.

**Comment by diegogangl** [comment]
I would say this is mostly done, since the info is on the website and we are clearly leading people there
