### ISSUE TITLE
In the due date (and similar) treeview columns, the "now", "soon", "someday" strings don't show up in their translated versions, although others do

### ISSUE THREAD

**Issue by nekohayo** [getting-things-gnome/gtg#357]
Let's say you run with `LANG=fr_CA.UTF8 ./launch.sh`. In the main window, in the due date column (and probably also the start date, closure date, etc.) these strings will show up translated:

* Today
* Tomorrow
* In X days
* etc.

But not these ones, even if they are picked up by gettext for the .pot and translated in fr.po:
* now
* soon
* someday

The last time I looked at it, I couldn't figure out why, because the code in GTG/core/dates.py and GTG/gtk/browser/main_window.py didn't seem to do something particularly wrong...

**Comment by Neui** [comment]
Seems to have a similar problem to #362

In this case, the [`dates.py` file also initializes the translated strings](https://github.com/getting-things-gnome/gtg/blob/abe2a9110dd0fc6a46f2d095013972877ea67d78/GTG/core/dates.py#L43-L48) before gettext (the translation library) is initialized.
An workaround could be copying that dictionary to [`to_readable_string`](https://github.com/getting-things-gnome/gtg/blob/abe2a9110dd0fc6a46f2d095013972877ea67d78/GTG/core/dates.py#L445) (and indent it properly, because Python), but that would (I assume) always recreate the dictionary that is otherwise static and thus not that efficent.
