### ISSUE TITLE
Document the standard keyboard shortcuts to fold/unfold treeview items

### ISSUE THREAD

**Issue by 73** [getting-things-gnome/gtg#408]
Hi!
I am just new to gtg. 

Given I have tasks with subtasks, I would like to un-/fold them by the keyboard shortcut `right` and `left` (like nautilus).
It does not seem to work.

Thank you very much!
--73

**Comment by Neui** [comment]
Just a side note, shift+arrow keys works, as do the plus and minus keys (where it seems the former expands all subtasks where the latter just the one). These are by GTK, and [there is a issue about allowing using the unmodified left and right keys](https://gitlab.gnome.org/GNOME/gtk/-/issues/717).
Apparently, unmodified left and right keys can be used to navigate between cells in a row. Maybe keep this in mind if GTG adds something like being able to change the date with just a click.

**Comment by 73** [comment]
Oh. I did now thank you @Neui that solves the issue!

**Comment by nekohayo** [comment]
In that case I think it would be worth documenting in the keyboard shortcuts window and/or user manual, because even I did not know that keyboard shortcut existed with standard GTK!

However the big question is, if @diegogangl eventually decides to provide an alternative to GtkTreeview in liblarch, whether that'll need to be revisited and reimplemented or redocumented...

**Comment by vansia43** [comment]
Addressed by #514 and #513
