### ISSUE TITLE
GTK/window style not respected by gtg flatpak version

### ISSUE THREAD

**Issue by stefabat** [getting-things-gnome/gtg#448]
Hi,

I just installed GTG from flathub, and it works nicley, amazing work!
However, in GNOME 3.36.4 (distro Manjaro) the applications style (set in the Tweaks app) is not respected, instead it is the default one.

The Flatpak version is 1.8.1 and GTG version is 0.4.

**Comment by nekohayo** [comment]
I don't know if the Flatpak package explicitly sets/enforces the official GTK stylesheet ("Adwaita"), but as the Flatpak docs state, "Flatpak applications cannot directly use the system theme."

Personally... I consider that to be a "feature"; i.e. the app would appear "as tested and as intended by developers". Otherwise it's impossible to test every distro and theme/style combination and dealing with the [different UX or potential breakage](https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale), and it's also making it more complicated to document the app in a standardized way... for example on Ubuntu's theme the colors are completely different, the icons are different, etc.

This is just me saying this (not necessarily the opinion of other GTG contributors, I haven't asked around), but as someone who has contributed to multiple desktop apps I am in agreement with what is said in [this manifesto](https://stopthemingmy.app). I'm already going through the effort of testing with Ubuntu's theme in addition to the official GTK theme, but that's an "extra" and if something is broken in Ubuntu or other distros because of their themes, my personal opinion is that the only officially supportable platform is Adwaita.

That said, it is sometimes possible for you (as a user) to use your themes with flatpak apps. See https://docs.flatpak.org/en/latest/desktop-integration.html#theming

**Comment by stefabat** [comment]
Alright, I have to say it's the first time I use flatpak so I didn't know theming is not officially supported.
So, actually, I agree with your point of view.

A follow-up question though, I suppose that if I compile GTG from source I will get the application styled according to the system theme?

**Comment by stefabat** [comment]
Alright, I have to say it's the first time I use flatpak so I didn't know theming is not officially supported.
So, actually, I agree with your point of view.

Thanks for the last link, it works, I am able to set the theme in that way.

A follow-up question though, I suppose that if I compile GTG from source I will get the application styled according to the system theme?

**Comment by nekohayo** [comment]
Yep, when running the version from source, distro package, or from a git checkout, it uses whatever themes you've set with gnome-tweak-tool.

I guess I'll consider this question resolved then :)
