### ISSUE TITLE
[feature request] Choosing where data is stored to sync in Nextcloud files

### ISSUE THREAD

**Issue by tykayn** [getting-things-gnome/gtg#473]
hi, i wanted to find an easy way to save the data of GTG.
An easy thing would be to add the ability to let users choose where to store data, so that we could save these GTG config and data in a Nextcloud folder or any synced folder by any other client software.

**Comment by diegogangl** [comment]
Hi! Why not use symlinks? Having a custom location where we read files from would force us to expand the flatpak permissions to the entire filesystem, which kind of defeats the purpose of permissions (and the XDG dirs standard). Plus it would bring a number of tricky problems when writing and loading files.

**Comment by nekohayo** [comment]
Yesh, I agree that this looks like a difficult to accomplish goal, with a potential workaround (symlinks) for those who really want it. But just putting this onto a cloud or auto-synced folder is asking for trouble, because I would imagine you could end with some conflicts/corruption if you open that data on two computers at the same time. Personally, I use [Unison](https://www.cis.upenn.edu/~bcpierce/unison/) to sync my GTG data folders over SSH/SFTP, and Unison lets me sync any folders on my system due to that, but I have to be very careful to use GTG on only one computer at once... so I'm not sure it's wise for us to complexify the codebase to let users put data folders into NextCloud or Dropbox or others synced folders like that, sorry! Again, if you really want to do that, you can still do it with symlinks at your own risk.
