### ISSUE TITLE
Plugin dialog: Hamster unclear "dbus" dependency (& stacks)

### ISSUE THREAD

**Issue by Neui** [getting-things-gnome/gtg#492]
The [Hamster plugin only uses the `dbus-dependencies` key](https://github.com/getting-things-gnome/gtg/blob/144814c16723fa9d00e17e047df5d79ab443fc5f/GTG/plugins/hamster.gtg-plugin):
https://github.com/getting-things-gnome/gtg/blob/144814c16723fa9d00e17e047df5d79ab443fc5f/GTG/plugins/hamster.gtg-plugin#L8

However, it'll just show that it needs the "dbus" python module:
![2 "dbus" dependencies](https://user-images.githubusercontent.com/1196130/96504104-830aad80-1254-11eb-8149-7c51ee925b74.png)

Bonus: Upon opening the plugin window multiple times, it'll stack:
![3 "dbus" dependencies](https://user-images.githubusercontent.com/1196130/96504137-93228d00-1254-11eb-88ae-e6595d818393.png)

**Comment by flavin** [comment]
Hi @Neui & @diegogangl 
I'm not sure what is the proper way to solve this.

to avoid the duplication I suspect we need just to add the `dependency` of dbus in the config file
this will avoid to enter in the else here and appending a new one.
https://github.com/getting-things-gnome/gtg/blob/master/GTG/core/plugins/engine.py#L112-L116

and why probably the plugin didn't depend on dbus, because it was a project module removed here:
https://github.com/getting-things-gnome/gtg/commit/bedcae9acc6466e527fc6909d764a9e01b722f5c#diff-75d233079e760bf9aa1474d733dd045a2d996d45efcfb4538d79cd9b7698bbec

also dbus missing dependencies is not being used, not sure what should we do with `dbus-dependencies` 
https://github.com/getting-things-gnome/gtg/commit/931427b1d9f1d00c3b7ee6210802b7f9b01349c1

**Comment by flavin** [comment]
@Neui can you check this PR https://github.com/getting-things-gnome/gtg/pull/497 to avoid appending once and once again dbus
