### ISSUE TITLE
Fresh install : cannot launch GTG

### ISSUE THREAD

**Issue by WhilelM** [getting-things-gnome/gtg#518]
version v0.4-242-gd7bbcd5b

Installed meson backport (not indicated in readme).

```
~/gtg$ ./launch.sh
Running the development/debug version - using separate user directories
Your data is in the 'tmp' subdirectory with the 'default' dataset.
-----------------------------------------------------------------------
ninja: Entering directory `.local_build'
ninja: error: loading 'build.ninja': No such file or directory
/home/whilelm/gtg/scripts/debug.sh: ligne 61: ./.local_build/prefix-gtg.sh: Aucun fichier ou dossier de ce type
```

I don't know what to do to generate this build.ninja file.

**Comment by Neui** [comment]
Could you do `rm -rf .local_build` and try again?
The script would only run `meson` manually when that directory doesn't exists yet to generate it, and delegate it afterwards to `ninja`, which automatically should re-run `meson` when needed. Since it seems you had to do something to install `meson`, it might've generated the folder but not the build files in previous attempts.
