### ISSUE TITLE
Putting focused main window on top of the stack

### ISSUE THREAD

**Issue by radoslaw-gajos** [getting-things-gnome/gtg#528]
I think that focusing on main window should put it on top.

**Comment by nekohayo** [comment]
If you are talking about the main window (that lists all the tasks), I've changed that on purpose in 0.4 compared to 0.3.x because:

* I tend to have a bunch of tiny individual task windows open during the day, and they are hell for window management, unless they are "utility" windows like they are now and act as a single unit with the main window. They are meant to be transient anyway (personally speaking, if I have more than 2-3 open at the same time while I'm working then I know something is wrong :)
* The main window kept obscuring the view of the individual task windows and this had been bothering me for 10 years as a user.

With task windows being utility windows now, I no longer have to fight with the app for window management. If I don't want a task showing on top of the window, I simply close that task window (or move it to another screen), and I find it _much_ easier to manage that way; in the previous approach, I constantly had to "fish out" individual task windows from behind the main window, so I'd much rather not go back to that.

That said, if you're interested in a single-window interface as an alternative, that would be #275 !
