### ISSUE TITLE
Unable to install GTG from Flatpak on Debian 10

### ISSUE THREAD

**Issue by iaeiou** [getting-things-gnome/gtg#537]
I successfully installed GTG on Debian 10 using Flatpak:

    flatpak install flathub org.gnome.GTG

but when I try to start with `flatpak run org.gnome.GTG` I get the following error:

```
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python2.7/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: DescribeAll is not a valid method of interface org.gtk.Actions
```

I've even tried with `sudo flatpak run org.gnome.GTG` and I get this

```
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
2021-01-10 11:05:04,695 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found
2021-01-10 11:05:04,699 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found
2021-01-10 11:05:04,700 - INFO - cleanxml:openxmlfile:176 - No suitable backup was found

(gtg:2): Gtk-CRITICAL **: 11:05:04.722: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(gtg:2): Gtk-CRITICAL **: 11:05:04.722: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

(gtg:2): Gtk-CRITICAL **: 11:05:04.722: _gtk_style_provider_private_get_settings: assertion 'GTK_IS_STYLE_PROVIDER_PRIVATE (provider)' failed

```

Any hint?

**Comment by iaeiou** [comment]
It works fine when it's installed from 'Software', the package manager. I'll try to investigate it asap, you can assign this ticket to me

**Comment by nekohayo** [comment]
In any case, do not use sudo to launch desktop apps. Not only is that a safety risk, it's also the reason why you got those "Unable to init server: Could not connect: Connection refused" errors: the app was trying to launch graphically on a nonexistent display server, since you were executing it as root but you were running your graphical session as your own non-root user.

Other than that, I don't see why it would be different if installed from the GUI vs installed from the commandline. Maybe you needed to reload your desktop session or you rebooted in the meantime and then it started working? I'd bet if you tried running normally from the commandline now it would work, unless something is messed up with your terminal's environment variables or something. Will leave this open for now, in case you find the explanation in the coming days, but otherwise since it works with the GUI install, unless there is a demonstrated bug, this could be closed.

**Comment by iaeiou** [comment]
I did a new install on a fresh Debian and everything works fine now.

Thank you! (BTW, GTG is a critical tool for me, using it everyday, I really appreciate the work you do on it - super thanks)

I'm closing this ticket
