### ISSUE TITLE
Minimise to system tray

### ISSUE THREAD

**Issue by mariomadproductions** [getting-things-gnome/gtg#548]
Feature request: Minimise to system tray

I think this would be useful if you often need to access gtg, but don't want it mixed in with the more "temporary" windows (browser, terminal, text editor etc).

**Comment by diegogangl** [comment]
We have a plugin that does this, but it's unmaintained and abandoned:
https://github.com/getting-things-gnome/gtg/tree/master/GTG/plugins/unmaintained/notification_area

This won't be in core, since we are a Gnome app and the systray isn't part of the enviroment anymore, but if someone wants to bring this plugin back to life go ahead!

**Comment by nekohayo** [comment]
Hijacking close to minimize into a system tray icon is an endless source of bugs and usability issues (I know from experience with previous/other applications). Relying on the try icon anti-pattern opens up the possibility of users having the app still running in the background without their knowledge, or broken things because their desktop environment doesn't have a UI for handling tray icons, etc. I'd say if you want to minimize, just minimize the app normally, or move it into its own virtual workspace.

So I would definitely say "wontfix" for core, and if someone wants to go through the crazy hoops to make it work as a plugin they can try to do so, but then they have to promise to maintain it and be there to fix issues that will show up, and such issues almost inevitably will occur. I think it's not even possible to do a tray icon easily anymore, as GtkStatusIcon has been deprecated from GTK since 2014 (in version 3.14).

**Comment by mariomadproductions** [comment]
Well having a dedicated "minimise to tray" menu option would be a solution to the "hyjacking close" thing, but you have a good point about compatibility with different desktop environments. I guess a better solution to this whole thing would be if desktop environments themselves allowed you to minimise any window into a system tray (or similar toolbar).

**Comment by davidhealey** [comment]
Another workaround for this issue is to use kdocker and a service to restart it each time it's closed.

This is the (user level) gtg.service file I'm using, placed in ~/.config/systemd/user/

```
[Unit]
Description=Getting Things GNOME Service
After=network.target

[Service]
Type=simple
ExecStart=kdocker -d 2 -n "Getting Things GNOME!"  gtg
Restart=always
RetartSec=5
Environment=DISPLAY=:0
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

[Install]
WantedBy=default.target
```
