### ISSUE TITLE
Ability to toggle showing all tags (including unused ones)

### ISSUE THREAD

**Issue by asakura42** [getting-things-gnome/gtg#560]
One of the most important things for me to manage tasks is tags. I like tags and it's handy. But if I mark as "done" the last task with some tag, that tag disappears from the list and I have to either dig through the tasks I've done (sometimes useless if they are deleted) or make up a new one (even though the tag exists) next time. This is inconvenient. Is there any way I can see all the tags I've created? Or, let's say, display all tags, including tags for done tasks? I looked around in the settings and couldn't find anything.

**Comment by diegogangl** [comment]
I've thought about this in the past. Maybe we should have an option to autohide tags when empty or not

**Comment by nekohayo** [comment]
Either it could be something in the preferences (or a checkbox in the main menubutton), or there could  be an inline toolbar in the tags sidebar that has a set of three linked buttons acting as mode switchers:
* Show only tags that are currently used AND actionable (like GTG 0.3.x)
* Show only tags that are currently used (whether actionable or not; like GTG 0.4/git)
* Show all tags (including unused ones; particularly the ones that had been customized); this would arguably turn the sidebar into a "tag manager"...

In a somewhat related vein, it's been nagging me that the tag tasks counters in the sidebar always show the _total_ open items count; I thought maybe there could be a switch to control that, but in practice I don't see why I would care to have all those types of numbers be configurable and add UI complexity while it could be automatically like in 0.3.x, so that's issue #170.

**Comment by nekohayo** [comment]
The git `master` version shows tags with 0 items in it now, so I guess this is kind of solved. Follow-up is #1007 and #1011.
