### ISSUE TITLE
When will v0.5 be released?

### ISSUE THREAD

**Issue by puelp** [getting-things-gnome/gtg#574]
I didn't know where to ask this.

It has been almost a year since the last release and I couldn't find any info on what the timeline for the next release was.

**Comment by diegogangl** [comment]
You can see where we are in the milestone:
https://github.com/getting-things-gnome/gtg/milestone/3

...aaaand we're 3 months past due. We were pretty close, but things got delayed due to personal (family health) reasons. We're currently beta testing 0.5 and we're getting pretty close to release IMHO. I've been using the dev version daily without any issues and there haven't been too many reports lately.

You can always read about GTG's whereabouts in Jeff's blog: https://fortintam.com/blog/gtg-data-format-v2-merged/

**Comment by Neui** [comment]
On a related note, since it is just testing phase it would be the great time to update the `po`-files in the repository so new translations can be based on the new version without having to do it themselves.

**Comment by diegogangl** [comment]
@Neui Good point, done!

**Comment by nekohayo** [comment]
Thankfully, various users have been testing and reporting bugs in the current git version in the last few days, and this helps a lot. Let's tentatively aim for the beginning of April (April 1st? :) if we can and there are no catastrophic bugs reported (and hoping I actually have the time to prep all the announcements stuff, I'll _try_, but I might be over-promising here because my next 6 weeks are expected to be crazy).

In theory it's "just" a matter of writing the blog post (ha ha), preparing social media & press outreach, and going through the procedure [in this file](https://github.com/getting-things-gnome/gtg/blob/master/docs/contributors/release%20process%20and%20checklist.md)... oh I see I somehow forgot to document, in that markdown file, that we also have to update the [appdata XML](https://github.com/getting-things-gnome/gtg/blob/master/data/org.gnome.GTG.appdata.xml.in.in) stuff. And maybe there are other new release procedures/gotchas that appeared since 0.4 that I'm forgetting about?

By the way @vansia43 if you want to land some last minute documentation changes (or help with figuring out what to say in that blog post, if you have too much free time) then now you know the tentative timescale :)

**Comment by puelp** [comment]
Thank you for all the replies, I can't wait!

Will the Flathub version be updated at release time?

**Comment by nekohayo** [comment]
It is now released, and yes the Flathub version has been updated at the same time as the announcement here: https://fortintam.com/blog/gtg-0-5-released/
