### ISSUE TITLE
gtg "forgets" activated plugins

### ISSUE THREAD

**Issue by silberzwiebel** [getting-things-gnome/gtg#59]
Hope its the right place here to report the following bug:
I'm using the "Notification Area" Plugin with the option to hide gtg at the start. However, from time to time, gtg "forgets" what plugins are active and thus shows up at system boot, which is annoying.
All other active plugins are in-active, too.
So far, I don't know how to reproduce. Sometimes, it happens, sometimes everything is fine.
I'm using Fedora 20 with gtg 0.3.1. I've also enabled the gnome shell 3.12 repo [1], maybe this is related?

[1] https://copr.fedoraproject.org/coprs/rhughes/f20-gnome-3-12/

**Comment by lcabrini** [comment]
I've noticed this is well. It happens if I log out of Gnome with GTG running. As long as I quit GTG before logging out/shutting down it is fine. There are a few other things that happen as well when GTG is not properly quit. Some settings seem to go back to default values, such as the sort order of the tasks.

I'm on Debian Jessie (testing), running (mostly) Gnome 3.14 and GTG 0.3.1.

**Comment by aphirst** [comment]
I can confirm too that this is to do with when GTG is improperly quit. You can't even workaround it by making the config file read-only, as in that case GTG simply fails to run at all! Which is a bit strange, but whatever.

**Comment by digsig** [comment]
bump! 
IMO this is priority:high!
2018 and still the same problem with gtg from on debian (v0.3.1) and mint repositories, too.

rebooting deaktivates all plugins.
rebooting messes up the preferences.

**Comment by nekohayo** [comment]
This project was abandoned from 2015 to 2019. I'm now trying to resurrect it and get a release out of the door.

Please bring a patch to the table or this bugfix probably won't happen. I'm otherwise considering killing off the "tray icon" entirely to get rid of unmaintained (and buggy) code paths and reduce the testing complexity.

**Comment by lcabrini** [comment]
Sorry to ask but does the "tray" still exist? I haven't seen it for years, and not really missed it either (on Gnome, that is).

I can understand that users of other desktops may still have a tray and want to use it, but if it turns out that the majority of gtg users are also Gnome users and the tray is a thing of Gnome's past, then it seems to me a good candidate for removal.

**Comment by silberzwiebel** [comment]
Not using `gtg` since a long time, but happy to see the tray icon going (although there is an GNOME Shell extension for tray icons, this seems to be an outdated concept). IIRC the issue was affecting other plugins, too, though (i.e., that the plugins were deactivated).

Thanks for resurrecting the project, looking forward to a release :)

**Comment by diegogangl** [comment]
Gave this a quick test in master and plugins stay activated (the ones that work at least)

**Comment by diegogangl** [comment]
Not happening in Master (even if I xkill gtg)
