### ISSUE TITLE
Help installing from git & meson

### ISSUE THREAD

**Issue by XaviP** [getting-things-gnome/gtg#596]
Hi gtg
I'm trying to install with this steps:
```
git clone https://github.com/getting-things-gnome/gtg.git
mkdir gtg-build
meson gtg gtg-build
cd gtg-build
meson install
```
Everything seems ok, but when I try to launch:
```
gtg
Traceback (most recent call last):
  File "/usr/local/bin/gtg", line 78, in <module>
    from GTG.core import info
ModuleNotFoundError: No module named 'GTG'
```
Edit: Xubuntu (xfce) 20.04 with all dependencies from README installed.

**Comment by Neui** [comment]
Can you try `mv /usr/local/lib/python3.8/site-packages/GTG /usr/local/lib/python3.8/dist-packages/`? (Replace `python3.8` with the python version you're using, or whatever directory you can find the GTG folder in).

Seems [Debians Python uses the `dist-packages` directory rather than the default `site-packages`](https://wiki.debian.org/Python#Deviations_from_upstream), which Ubuntu follows. On Ubuntu 20.04 with the command `python3 -c 'import sys; print(sys.path)'` I get `['', '/usr/lib/python38.zip', '/usr/lib/python3.8', '/usr/lib/python3.8/lib-dynload', '/home/neui/.local/lib/python3.8/site-packages', '/usr/local/lib/python3.8/dist-packages', '/usr/lib/python3/dist-packages']` (`site-packages` not mentioned except the user-local one), but the build system installs in `site-packages` folder.

**Comment by XaviP** [comment]
> Can you try mv /usr/local/lib/python3.8/site-packages/GTG /usr/local/lib/python3.8/dist-packages/?

Yes, that works, thanks. Now I'm getting error with liblarch:
```
Traceback (most recent call last):
  File "/usr/local/bin/gtg", line 79, in <module>
    from GTG.gtk.application import Application
  File "/usr/local/lib/python3.8/dist-packages/GTG/gtk/application.py", line 28, in <module>
    from GTG.gtk.browser.main_window import MainWindow
  File "/usr/local/lib/python3.8/dist-packages/GTG/gtk/browser/main_window.py", line 28, in <module>
    from GTG.backends.backend_signals import BackendSignals
  File "/usr/local/lib/python3.8/dist-packages/GTG/backends/__init__.py", line 32, in <module>
    from GTG.backends.generic_backend import GenericBackend
  File "/usr/local/lib/python3.8/dist-packages/GTG/backends/generic_backend.py", line 33, in <module>
    from GTG.core.tag import ALLTASKS_TAG
  File "/usr/local/lib/python3.8/dist-packages/GTG/core/tag.py", line 30, in <module>
    from liblarch import TreeNode
ModuleNotFoundError: No module named 'liblarch'
```
which I've installed with:
```
pip3 install --user -e git+https://github.com/getting-things-gnome/liblarch.git#egg=liblarch
```

**Comment by XaviP** [comment]
Solved installing liblarch this way:
```
# Remove old liblarch installation first
rm .local/lib/python3.8/site-packages/liblarch.egg-link 
cd gtg-source/src/liblarch/
pip3 install --user .
```
Now gtg starts ok from command line and in the desktop.
Thanks!
