### ISSUE TITLE
Why is there a slight delay for heading style changes to be applied in the task editor?

### ISSUE THREAD

**Issue by DiegoIvanME** [getting-things-gnome/gtg#617]
I found this bug making a new task [video footage here](https://youtu.be/d_FaY1oC9N4)

Description of the Bug:

* Annoying font size change while writing

Testing environment:

* **Install**: Flatpak from Flathub: System
* **Distro**: Fedora 34 Beta
* **Version**: 0.5

**Comment by diegogangl** [comment]
Hi, it's not really a bug but rather a result of the parsing timeout. GTG waits a few milliseconds after you type to parse the text,  and that's when it applies the tags (like the title). It's only visible in titles and subtitles though.
We could look into lowering the timeout again so it's less perceptible.

pinging @nekohayo

**Comment by nekohayo** [comment]
Yup, works as expected, I wouldn't want us to sacrifice performance for a minor cosmetic detail.

**Comment by nekohayo** [comment]
The only way I could imagine "faster header styling" would be by having two timers instead of one:
* One faster timer "for the visuals" that parses the changes faster and applies them locally to TaskView _without_ propagating the changes to the rest of the app/backend
* One slower timer that commits the changes "to the rest of the app"

I don't know how feasible/do-able it could be while keeping the code clean, but if someone would like to investigate that path they're welcome to :)

Otherwise I don't see how this could be resolved without spamming the backend, and I really wouldn't want to go back to that; with GTG 0.5, in the past few days, my GTG has been so incredibly fast and smooth that I almost feel like I'm typing through air, i.e. "No way this is applying/saving the changes, this feels _way too smooth!_"
