### ISSUE TITLE
[Enhancement request] Polish up design

### ISSUE THREAD

**Issue by puelp** [getting-things-gnome/gtg#630]
I'm not a designer so it's hard for me to put this into words, but by 'polish up design', I mean small, intangible things that may seem inconsequential, like the margins of the task list or the sidebar.

Official GNOME apps just 'feel' right in this aspect (margins, padding, spacing, etc.). They feel comfortable, legible, and like there was thought put into it, etc, whereas by comparison, GTG's task list feels like an unwelcoming wall of text with relatively little thought put into presentation.

Also, the Preferences page does not match the design language used in the Preferences of GNOME 3.38/40 apps.

These are just two. There may be more intangible design elements that could be polished.

These aren't big bugs per se, and if this was KDE I wouldn't have given it a second thought. But GNOME is a beauty/design-oriented desktop environment, so I thought that it would be worth bringing it up.

**Comment by diegogangl** [comment]
Hey @puelp thanks for bringing it up. We're aware of that, but we're constrained by the old widgets we're using, and some code barely changed from the Gtk2 days. Changing all this is requires rewriting half the app, so it's going to take _quite_ some work.

There's already a few issues for this:

#278 
#276 
#553  (this is core + UI changes)

Could you open a new issue for the preferences window? I intended to re-write it to make it look more like epiphany's, but maybe you had some other ideas. Not sure if we can do it for 0.6, or if it's worth porting to libhandy when libadwaita is around though.
Also, open issues if you spot anything specific. 

Closing this one, since we already have issues dealing with the design topic. And it's better to tackle them one-by-one.
