### ISSUE TITLE
GTG won't open when pinned to dock/panel on KDE Plasma

### ISSUE THREAD

**Issue by Vitorvlv** [getting-things-gnome/gtg#651]
Not sure if this project has an interest in fixing bugs for other desktop environments. But I'll report it anyways. I have the flatpak version installed. I have also tried it in the default plasma panel, same behavior.

I've attached a short video showing the issue.

The notification says something like: "The file or folder python3 doesn't exist."

https://user-images.githubusercontent.com/26132870/116614207-0433b300-a910-11eb-8995-baa3b307e444.mp4

**Comment by nekohayo** [comment]
What if you add it as a favorite by dragging it from your launcher menu to the panel, instead of pinning it when it's already launched?

This sounds like a bug in how KDE Plasma handles application launchers, because I tried in:
* GNOME Shell's dash launcher
* The dash-to-panel extension
* The dash-to-dock extension
* Elementary's "plank" standalone dock application

...and they all handle it just fine, so unless it's something related to #638, I'm not sure what can be done on our side. How do other python apps handle themselves on Plasma in this scenario?

**Comment by Neui** [comment]
> so unless it's something related to #638

They're using flatpak, so they are (likely) using v0.5 which doesn't has that change.

**Comment by nekohayo** [comment]
Yeah I meant related to the issue "before it was fixed"; but that's just a wild guess, I doubt that'd actually change much in the way Plasma behaves...

**Comment by diegogangl** [comment]
Wild guess: The command should be something like `flatpak run org.gnome.GTG` (which is what you have in KRunner), but the dock is saving the process, or say, what flatpak runs inside the sandbox. Can you manually edit the entries in latte? Try using the flatpak command.

**Comment by Vitorvlv** [comment]
> What if you add it as a favorite by dragging it from your launcher menu to the panel, instead of pinning it when it's already launched?

it works, but not perfectly, this is the behavior now, i've used spotify, another flatpak app, as an example of the correct behavior:

https://user-images.githubusercontent.com/26132870/116627068-cee49080-a922-11eb-8ee1-0f1ea9f5f717.mp4

> How do other python apps handle themselves on Plasma in this scenario?

I might be wrong, but I believe Anki is a python app. It behaves as expected. If you have any other examples of python applications for me to try let me know, I don't know any other.

> Wild guess: The command should be something like flatpak run org.gnome.GTG (which is what you have in KRunner), but the dock is saving the process, or say, what flatpak runs inside the sandbox. Can you manually edit the entries in latte? Try using the flatpak command.

You can't manually edit entries in Latte. But I downloaded some more flatpak apps to try (spotify and obsidian), and they behave as expected. 

I've also gave gtg-git a try and same thing happens.

**Comment by Neui** [comment]
> I might be wrong, but I believe Anki is a python app.

I looked into it. It certainly has a sizable potion of python, but there seems to be a lot of rust.
Unfortunately, I couldn't really find the entry point, except that it was named "bin/Anki" (and is being copied to bin/anki according to the install.sh linux script). Downloading the linux binary version shows that the main executable is actually a normal executable rather than being a python script like we have.

Other projects using python are [Pitivi](https://flathub.org/apps/details/org.pitivi.Pitivi) and [D-Feet](https://flathub.org/apps/details/org.gnome.dfeet) (and possibly more on https://pygobject.readthedocs.io/en/latest/#who-is-using-pygobject), although they're also gnome/gtk apps.

What would be interesting is to find where the pinned items are saved and what they info they contain (particularity the path).
Personally, I'd try something like `grep -ri "Getting Things GNOME" ~/.local ~/.config` and look at the results.

**Comment by Vitorvlv** [comment]
Both Pitivi and D-feet, installed through flathub, worked as expected.

`grep -ri "Getting Things GNOME" ~/.local ~/.config`

didn't return anything. 


I've stumbled upon this Latte dock FAQ entry: https://userbase.kde.org/LatteDock/FAQ#My_launcher_and_its_window_are_not_associated_correctly_OR_my_launcher_is_using_a_low-resolution_icon.3F

Apparently it uses the .desktop file. To test this, I've pinned GTG to the dock by draggin it to to the dock and... wait

it works now

https://user-images.githubusercontent.com/26132870/116634054-77015600-a931-11eb-99ea-8af4c42b5c78.mp4

I was messing with the .desktop file and apparently broke it into working. 

A immediate difference I can see between this video I just sent and the others is that in the window preview you get when you put the mouse over the icon, now it says Getting Things GNOME! at the top. Before it used to say python3 and under Getting Things Gnome!

![Screenshot_20210429_212903](https://user-images.githubusercontent.com/26132870/116634387-42da6500-a932-11eb-9fe3-c9890420ae1b.png)

Now plasma is probably able to recognize it.

**Comment by Vitorvlv** [comment]
> Also latte suddenly stopped showing icons, and while trying to restart via killall latte-dock the entire VM just "shut down" instantly. 

Just a couple things: 

If you don't want to mess with Latte dock, you can just try it with plasma default panels. GTG has the same issue in them.

If you DO want to try it with Latte, make sure you're using the latest version from git. The 0.9 release in kubuntu repositories is not supported anymore. The latest one might behave a bit better.

**Comment by Neui** [comment]
I believe I found the function on the KDE side where it tries to determine the application: https://github.com/KDE/plasma-workspace/blob/add0a50ddae00d45bfc3dc25c4db7938129bed01/libtaskmanager/tasktools.cpp#L210 (According to latte and confirming via gdb it is at least calling that function)
One of the things to check is the name, so I tried to change the Name= on D-Feet and suddenly KDE/Latte gets the same problem.
To make GTG work via that we would be using "GTG" as the Name rather than "Getting Things GNOME!", but I don't think we want to change that.

The reason why GTG probably works on gnome is because [it explicitly looks for the GTK application id](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/a472657490892592ce34ad3bc095c013c0d75e56/src/shell-window-tracker.c#L426).

So the solution for KDE is as the FAQ mentions adding `StartupWMClass=Gtg` to the .desktop-file. Not `gtg` (all lowercase), since it seems the second value of `WM_CLASS` always starts upper-cased (for example look at some of the comments in the gnome code).
I am not sure if it works the same way for Wayland, since it seems `WM_CLASS` is X11-oriented.

Flatpak shouldn't be a problem since Latte just remembers the desktop file and thus does not need to deal with flatpak explicitly (and assuming flatpak doesn't mangle `WM_CLASS`)
