### ISSUE TITLE
Gamify does not count subtasks when closing the parent task

### ISSUE THREAD

**Issue by morhe-blip** [getting-things-gnome/gtg#655]
Description and reproduction:

Create a task with with n different subtasks. Mark the parent task as done with n open subtasks. The counter is increased by one instead of n (or n+1 don't know how this is counted)

**Comment by zeddo123** [comment]
I forgot about it, my bad. This does bring a issue though. When receiving the signal that a task has been marked as done, all subtasks of that task would be set to done. Thus there is no way to know which ones that were just set to done.
Example:
* Task A (Active)
   * Task A.1 (Done)
   * Task A.2 (Active)

Now if I set Task A to done, in the plugin I wouldn't be able to know which subtask was marked as done (Task A.1 or Task A.2 or both).
The easiest way we might be able to fix this issue is to be able to emit a signal when ever a task has been marked and which would make solving #654 implicit. @diegogangl, Is it even possible to emit signal in the Task class?

**Comment by diegogangl** [comment]
The Task class extends TreeNode which is not a gobject, so my guess would be no unless you also extend gobject. 
Maybe you could loop throught the subtasks while setting a task to done, and see which ones were active?

**Comment by zeddo123** [comment]
>Maybe you could loop throught the subtasks while setting a task to done, and see which ones were active?

There seems to be a race condition, so when the signal reaches the plugin all subtasks are already set as done.

**Comment by zeddo123** [comment]
I've been looking for the solution this whole week and I couldn't find a good solution.

@diegogangl is it recommended to extend the gobject? 
A simple solution is to pass the browser to the task object, but that does not seem to be a good design choice.

**Comment by diegogangl** [comment]
I don't think there would any issues adding gobject to Task

>  A simple solution is to pass the browser to the task object, but that does not seem to be a good design choice.

Wait, why do you need the browser? You already have access to the requester in Task (`self.req`)
