### ISSUE TITLE
Gnome window placement and resizing via keys

### ISSUE THREAD

**Issue by primal-buddhist** [getting-things-gnome/gtg#673]
Hi all

For most gnome applications, Super-Right moves the current window to the right and makes it half screen size. It's a very efficient way of getting two apps to sit size by side. Typically to use one as reference while you work in the other.

I have noticed that GTG does not react to Super-Right (or any of the super direction keys) at all and wondered why that was?

I also notice that the GTG window has a minimum width that would actually prevent it from being half a screen wide on my 1366x768 laptop.

A nice to have.

**Comment by diegogangl** [comment]
Yeah, we could probably remove the limitation or make it something really small. It won't look good initially but we'll get to make the UI adaptative at some point

**Comment by niconil** [comment]
with resolution 1920x1080 on my screen, GTG react as expected with Super-Right and Super-Left
if i change it to 1366x768 i can reproduce the issue

so the minimal width of the GTG window seems to be the real issue.

**Comment by nekohayo** [comment]
> The minimal width of the GTG window seems to be the real issue

You are correct.

> with the PR #677 i replace the label "Start Tomorrow" by a icon

Hmm, I'm a bit torn on this. The reason why it wasn't just an icon to begin with, is because it's hard to convey what it is with just an abstract/metaphorical icon... even though yes, a label can be fairly long.

Perhaps there can be a middleground/best-of-both-worlds approach here: @niconil do you think it would be possible to make your code detect the available screen resolution's width, factoring the GTG window's required/measured width, and then dynamically hiding/showing the label and icon? (or maybe you'll need to have two buttons and hide/show them). Essentially making it an "adaptive" (aka "responsive" in the web industry) UI. However it would need some sort of trick so that the window manager doesn't consider that button's width as part of the window's minimum width, so that it is considered half-tileable, I don't know if there's a way to do that...
