### ISSUE TITLE
Context for actionable tasks

### ISSUE THREAD

**Issue by famuvie** [getting-things-gnome/gtg#696]
Hi, I have a problem with my workflow and I could not figure out the "right" way of organising tasks. I'd appreciate some advice.
I organise my tasks hierarchically. Say that I have 2 tasks/projects with several steps each:

- Prepare materials for course X
  - find a suitable example dataset
  - prepare slides
- Write report for project Y
  - clean up data
  - make exploratory analysis

The Actionable tasks view then shows the four (blocking) sub-tasks (which is perfect) without any context. So I know that I have to clean up some data, but I don't know related to which project. 
Handling dozens of projects with many sub-tasks each (and often sub-sub-sub-tasks), I'd really like to have some reminder of the parent task (or even full hierarchy). I often find myself clicking on the task and opening parent tasks in order to figure out what the task was about!
A pop-up would perhaps suffice. 

Or perhaps is there a better way to organise tasks or use the tool to identify the context more easily? The only thing I thought of is giving the context I want in the task name. But I'm not comfortable with this solution as it leads to overly long and repetitive task names, and DRY.

Thanks in advance for your insight!
ƒacu.-

**Comment by Neui** [comment]
Also see #611 (or #240 for an idea via tooltips).

**Comment by cyphase** [comment]
I also organize my tasks hierarchically, sometimes with several levels. I know you're saying you don't want to do this, but I do put the context in the task name, if necessary. Sometimes it's clear without "additional" context, sometimes I include it in the prose of the task name, and sometimes I will start task names with "(hyphenated-project-slug)". For instance, I have a task right now with the name, "(digital-displays) Configure to start automatically on boot", along with several other tasks that begin with "(digital-displays)" – the hyphenated slug doesn't have to be the full project name, just enough so that you know what it is. This has the added benefit that all these related tasks begin with the same thing, so they're easier to spot, and search for. I also like being able to see that context anywhere I can see the task name, rather than having to hover over it or whatever.

**Comment by famuvie** [comment]
Yeah, thanks a lot. That helped.
I think using a project-slug/context into the description of the subtasks (which can be shown in the Actionable view) will work reasonably fine for me.
The tooltip approach from #240 would also be helpful.

Thank you again.
ƒacu.-
