### ISSUE TITLE
PT_BR translation not present

### ISSUE THREAD

**Issue by gleissonjoaquim3** [getting-things-gnome/gtg#698]
Hi ! Congratulations to everyone for the great work on this program!
I just installed GTG on fedora34 in flatpak, but for some reason the pt_BR language is not present. I saw in the source code that the file has ( https://github.com/getting-things-gnome/gtg/blob/master/po/pt_BR.po). Please can see...

**Comment by Neui** [comment]
If you look at the history of the file (click top right), #646 actually updated the translation in late April 2021, where GTG on Flatpak was released at the beginning of April 2021. In other words, the translation was done after the flatpak release, and since there hasn't been a release yet (seems we're all busy, for me at least next month I'll have more time to work on stuff).
You unfortunately need to wait, or build from git (seems we don't have documentation to install a non-development version, which basically boils down to run and configure an meson build)

**Comment by gleissonjoaquim3** [comment]
Thanks for the feedback ! I'll continue using and waiting for the next release. Thanks !

**Comment by nekohayo** [comment]
@gleissonjoaquim3 we're preparing to release 0.6 in the coming days (probably next week-end or something like that), and have updated the .pot file, so now is a good time to update your translation :)

**Comment by nekohayo** [comment]
Call for translators is issue #358, closing this ticket now targetted at the upcoming 0.6 release, since it's a user request actually.
