### ISSUE TITLE
Feature Request: Add Support for DecSync

### ISSUE THREAD

**Issue by BeatLink** [getting-things-gnome/gtg#704]

**Comment by nekohayo** [comment]
This seems like a fairly obscure/unknown project/protocol...
If someone wants to make a sync backend plugin for it _and_ promise to maintain it, then they are welcome to work on a pull request for this and state their intention to work on it here (see also our contributors' guide). Until then, especially since we have caldav sync about to land soon anyway, I'll consider that it won't happen unless someone steps forward to work on this.
