### ISSUE TITLE
Meson 0.60.0 build error: i18n.merge_file got unknown keyword arguments "build_always_stale"

### ISSUE THREAD

**Issue by yochananmarqos** [getting-things-gnome/gtg#720]
Building the `gtg-git` AUR package from 828c345d:

```
Build started at 2021-11-01T19:44:03.185274
Main binary: /usr/bin/python
Build Options: -Db_lto=true -Db_pie=true -Dprefix=/usr -Dlibexecdir=lib -Dsbindir=bin -Dauto_features=enabled -Dbuildtype=plain -Dwrap_mode=nodownload
Python system: Linux
The Meson build system
Version: 0.60.0
Source dir: /build/gtg-git/src/gtg
Build dir: /build/gtg-git/src/build
Build type: native build
Project name: gtg
Project version: 0.5.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Configuring prefix-gtg.sh using configuration
Configuring gtg using configuration
Configuring local-gtg using configuration
Program git found: YES (/usr/bin/git)
Running command: /usr/bin/git describe --dirty
--- stdout ---
v0.5-117-g828c345d

--- stderr ---


Configuring info.py using configuration

gtg/GTG/plugins/meson.build:19:7: ERROR: i18n.merge_file got unknown keyword arguments "build_always_stale"
```

**Comment by Neui** [comment]
Looks like a change introduces in Meson https://github.com/mesonbuild/meson/commit/6b1a80024c79876dc3b75f2b525be24ca8fe671a

Before "unused" arguments were directly passed to meson custom target command which uses "build_always_stale", but since that comment all "unused" arguments are cut. The [documentation suggests](https://mesonbuild.com/i18n-module.html) that these are "additional" to the arguments, but they clearly aren't now. Not sure if this is a meson "bug" or not.

"build_by_default" is passed through, so I am not sure if I need to specify "build_always_stale" or whenever just "build_by_default" is enough. It is a translators feature to quickly test the current translation (#555).

As a workaround, omitting "build_always_stale" should work when doing a simple build to install (e. g. in the patch step).

**Comment by yochananmarqos** [comment]
Yep, I already removed it as a workaround. I just figured I'd report it.

```
sed -i 's/    build_always_stale: true//g' GTG/plugins/meson.build
```

**Comment by Neui** [comment]
I looked into this again, but it isn't easily "fixable" if we want to keep regenerating the plugin files when the translation changes. `build_always_stale` is the easiest solution, but a proper solution would be depending on the PO files (https://github.com/mesonbuild/meson/issues/2621). They seem to intend that but that was a couple years ago...

And I really couldn't find a way to include the `.po`-files as a dependency for them, so either we're out of luck and have to re-mention the plugin situation again in the [translator document](docs/contributors/translating.md), ask meson to whitelist `build_always_stale`, or just don't support newer meson versions until they properly "fix that". (sorted by what I probably would most likely want to do to what I most likely don't want to do, since it is just a "small part" of the translation).

**Comment by Neui** [comment]
Actually I have re-read the new meson code again and it accepts an list of inputs which are forwarded, but only the first input is used for xgettext. 

Here is an untested implementation: https://github.com/Neui/gtg/commits/meson-xgettext-gtgplugin-regeneration-workaround2
Untested because it needs newer meson 0.57 for the [`fs.read()`](https://mesonbuild.com/Fs-module.html#read) function which I currently don't have installed (and "worried" about older distros). Alternatively we could explicitly list the po files, but I'd do it as a last resort.

**Comment by yochananmarqos** [comment]
@Neui I applied your commit and tried building with Meson 0.60.1:

```
+ exec meson setup --prefix /usr --libexecdir lib --sbindir bin --buildtype plain --auto-features enabled --wrap-mode nodownload -D b_lto=true -D b_pie=true gtg build
The Meson build system
Version: 0.60.1
Source dir: /build/gtg-git/src/gtg
Build dir: /build/gtg-git/src/build
Build type: native build
Project name: gtg
Project version: 0.5.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python3 found: YES (/usr/bin/python3)
Configuring prefix-gtg.sh using configuration
Configuring gtg using configuration
Configuring local-gtg using configuration
Program git found: YES (/usr/bin/git)
Configuring info.py using configuration
WARNING: Project targeting '>= 0.51.0' but tried to use feature introduced in '0.57.0': fs.read.
Configuring org.gnome.GTG.appdata.xml.in using configuration
Configuring org.gnome.GTG.desktop.in using configuration
Configuring org.gnome.GTG.service using configuration
Program xgettext found: YES (/usr/bin/xgettext)
Build targets in project: 71
WARNING: Project specifies a minimum meson_version '>= 0.51.0' but uses features which were added in newer versions:
 * 0.57.0: {'fs.read'}

gtg 0.5.0

  User defined options
    auto_features: enabled
    buildtype    : plain
    libexecdir   : lib
    prefix       : /usr
    sbindir      : bin
    wrap_mode    : nodownload
    b_lto        : true
    b_pie        : true

Found ninja-1.10.2 at /usr/bin/ninja
ninja: Entering directory `/build/gtg-git/src/build'
ninja: error: '/build/gtg-git/src/gtg/po/.po', needed by 'GTG/plugins/export.gtg-plugin', missing and no known rule to make it
```
