### ISSUE TITLE
App hangs with recurring task that lands on Feb 30th

### ISSUE THREAD

**Issue by paulaylingdev** [getting-things-gnome/gtg#765]
Found in version 0.5, flathub on Ubuntu 21.10

# How to reproduce

1. Create a task with a recurring date of the 30th of each month
2. Mark the task as done until it hits 30/01/2023
3. Mark the task as done and the App hangs and must be force quit

# Expected Behavior

1. App not to crash
2. Select a reasonable alternative?
  - 28/02 Feb
  - Or 29/02 if leap
  - Alternatively skip to 30/03 (not ideal)

**Comment by paulaylingdev** [comment]
Logs from CLI:

```
$ flatpak run org.gnome.GTG
GNOME keyring not found, passwords will be not stored after restarting GTG
Gtk-Message: 19:50:09.060: Failed to load module "canberra-gtk-module"
```

Nothing is logged when crash happens

**Comment by diegogangl** [comment]
Thanks for reporting! I can confirm this happens in Master too.
Summoning @zeddo123

**Comment by Neui** [comment]
I wonder if the same happens when you do it on 31<sup>th</sup> of March, since April only has 30 days?

**Comment by diegogangl** [comment]
Something even more interesting happens, it jumps the entire month over to the next one that has 31 days

**Comment by Neui** [comment]
This is the stack trace (on master) where the application gets stuck in (found out by `./launch.sh -p 'python3 -m pudb'`, reproduce, then CTRL+C in the terminal to break and investigate in [pudb](https://documen.tician.de/pudb/starting.html)):

```
get_next_occurrence [Task] task.py:400
duplicate [Task] task.py:135
duplicate_recursively [Task] task.py:149
set_status [Task] task.py:205
on_mark_as_done [MainWindow] main_window.py:1299
mark_as_done [Application] application.py:357
run [Application] Gio.py:43
<module> gtg:153
```

Which is inside https://github.com/getting-things-gnome/gtg/blob/8c5c4c233094f13e833a21b52f645f25540adab3/GTG/core/task.py#L380-L412

Both `nextdate` and `self.due_date` stay equal, so there is the infinite loop. `parse_from_date()` calls `_parse_only_month_day_for_recurrency()`:

https://github.com/getting-things-gnome/gtg/blob/8c5c4c233094f13e833a21b52f645f25540adab3/GTG/core/dates.py#L464-L494

`string` is  `'30`, `self_date` is `datetime.date(2023, 1, 31)` and result is `datetime.date(2023, 1, 30)`, so it eventually reaches line 486, but since 30<sup>th</sup> of Feburary doesn't exists, line 490 fails and then `result` is returned as-is (and gets stored to `nextdate`).

I think the best way for this specific issue is to modify that function at `if` at the end to try using the latest date if `mday > latest_day_of_the_next_month` (so it gets moved to the end of the month, which might be more what you would expect)

**Comment by diegogangl** [comment]
Wouldn't it be easier to use timedelta and have it rollover automatically? The stuff between 476-492 could be replaced with `self_date + datetime.timedelta(days=mday)` (unless I'm missing something)

**Comment by Neui** [comment]
> Wouldn't it be easier to use timedelta and have it rollover automatically? The stuff between 476-492 could be replaced with `self_date + datetime.timedelta(days=mday)` (unless I'm missing something)

`mday` is the day of the month, so using the first of every month `mday` would be `1`, so advancing by one day doesn't make any real sense. Looking at the docs, I haven't (quickly) found anything either that would "advance" an month for us. `timedelta` doesn't have a `months` parameter, and using something like `days=31` probably works, the resulting date might be rather not expected however (since it would move it to the beginning of an month).

**Comment by diegogangl** [comment]
Ah you're right. Your solution is the best way

**Comment by zeddo123** [comment]
>I think the best way for this specific issue is to modify that function at if at the end to try using the latest date if mday > latest_day_of_the_next_month (so it gets moved to the end of the month, which might be more what you would expect)

`calendar` can be used here to `latest_day_of_the_next_month` with `monthrange`.
