### ISSUE TITLE
Enter task in quick-add, but open a selected task rather than creating a new one

### ISSUE THREAD

**Issue by tkdchen** [getting-things-gnome/gtg#78]
Version: dev version

Reproduce steps:
- select an arbitrary task in task browser
- then, decide to add a new task, go to quick-add and enter some text
- press enter, this issue happens. the selected task is opened, but adding the new task is the one should happen.

Workaround is to unselect the task before press enter in  quick-add.

**Comment by jakubbrindza** [comment]
This issue was fixed when rebuilding the entire search functionality in #137 

Please, try pulling the latest dev version, you should not be having this problem (at least I'm not seeing it anymore :)). 

I'm closing it here, but if you find it again, please, reopen, I'll have a deeper look into the issue :blush:
