### ISSUE TITLE
Release 0.6 Beta On Flathub

### ISSUE THREAD

**Issue by thegranddesign** [getting-things-gnome/gtg#793]
Hey all, I'm currently evaluating GTD apps and would love to test this out.  Unfortunately full CalDAV integration is going to be a requirement for me.  It looks like 0.5 disabled synchronization (mine is currently greyed out even with `python-caldav` installed) and 0.6 added a rewritten CalDAV module.

Is there any chance we can get 0.6 released to Flathub's beta repo so we can test it out?  It looks like the most recent version on there is 0.4 beta.

Thanks for all the hard work!

**Comment by Neui** [comment]
If I remember correctly, the 18<sup>th</sup> of February  (or close to it) was planned for the v0.6 release. ([The milestone](https://github.com/getting-things-gnome/gtg/milestone/4) currently shows the 17<sup>th</sup>...).

**Comment by nekohayo** [comment]
For the stable release: I have been delayed in finishing up my blogging frenzy for the actual release, and I thought we still had issue no. 785 going on, but turns out it was fixed a couple days ago so in theory that's no longer a blocker. Still, it's nicer if we release a beta for people to try out in the meantime.

For the beta: if @diegogangl has time and can update the beta flathub package to replace 0.4 by it, that'd make sense... then we can take some more days to prepare for the actual release and let translators show up.

**Comment by diegogangl** [comment]
I've got the beta manifest working, but I'm getting delayed by some new critical error. Also we should bump app version before pushing the beta. Should I go ahead, or do you have that in your release branch @nekohayo ?

**Context:** Startup

```python-traceback
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/GTG/gtk/application.py", line 110, in do_startup
    for backend_dic in BackendFactory().get_saved_backends_list():
  File "/app/lib/python3.9/site-packages/GTG/backends/__init__.py", line 179, in get_saved_backends_list
    dic["first_run"] = True
TypeError: 'NoneType' object does not support item assignment
```

**Software versions:**
* Getting Things GNOME! 0.5.0
* CPython 3.9.9 (main, Nov 10 2011, 15:00:00)   [GCC 11.2.0]
* GTK 3.24.31, GLib 2.70.2
* PyGLib 3.42.0, PyGObject 3.42.0
* Linux-5.16.5-200.fc35.x86_64-x86_64-with-glibc2.33

**Comment by diegogangl** [comment]
Ok, fixed. The beta manifest is ready to be pushed, waiting on version bump

**Comment by thegranddesign** [comment]
What an amazing response!  I'll definitely be donating!

**Comment by nekohayo** [comment]
Made a liblarch 3.2.0 release now, and a 0.6 version bump in my personal repo's release prep branch, for @diegogangl to be able to review and publish the GTG 0.6 release candidate with flatpak; I'll try to make a blog post about it too.

**Comment by kocio-pl** [comment]
> Hi, yes we still haven't tagged and updated but it should be real soon.

Yikes... :sweat_smile:  I just started to update Polish translation from 2009 probably and hoped I have at least few days to finish it properly. Should I create a pull request ASAP to not miss the train (there was a POT update, so I'll try to at least include that) or it'd be better to spend like 2-4 days to make it complete and coherent?

**Comment by thegranddesign** [comment]
@kocio-pl this is just for a beta release not for the final. :wink:

**Comment by kocio-pl** [comment]
Great, thanks... I can still make a pull request for beta if you think that makes sense.
But since I try to make as good localization as it gets, I've found some problems that affect the final user experience. There are details like:
- missing translation source for a Hamster button and a task menu item 
- some hardcoded tags in the user guide (like `@errands` and `@waitingfor`)
- `@money.` tag, which was supposed to be just another occurrence of  `@money` tag in the task description, but it looks like dots are treated as part of a tag, while commas are not
- "streak" meaning in Gamify is unclear to me - is it how many days a user is in the game or what? dictionary proposed me a lot of meanings of this word
- "Send via e-mail" is indented in the task menu

and some more, but I'm unsure where to report them, since they are small. Is this ticket a good place for them?

**Comment by nekohayo** [comment]
> missing translation source for a Hamster button and a task menu item

Hmm you are right, it seems there are a bunch of strings not marked for translation in the hamster plugin (also many of that plugin's files are not declared in the `POTFILES.in` file), which I never caught/realized as I don't have hamster installed (it's not available in Fedora). Probably best to file a standalone ticket so that someone who has the ability to not only make the changes but also test them (maybe you or @flavin?) can do that for the next release cycle (I suspect now would be a bit too rushed, but I think we'd accept such a fix that _adds_ (rather than "modifies") newly translatable strings anytime, even if we're close to the release)

> some hardcoded tags in the user guide (like `@errands` and `@waitingfor`)

Yeah I noticed that, but never quite found a way to solve that problem...

> dots are treated as part of a tag, while commas are not

I wonder if they should/shouldn't be; probably shouldn't, in which case it's a code fix rather than a sample docs fix? I'll let @diegogangl decide as he's been the one messing with tags and file formats ;)

> streak" meaning in Gamify is unclear to me

It's a "streak of consecutive days where you have accomplished the daily goal", I think (I'm just guessing, haven't looked at the code, but someone could probably easily add a comment for translators there...).

> "Send via e-mail" is indented in the task menu

I noticed that as well, but never found why it happens, though that's certainly a code issue rather than anything to do with translations... you could file this as a standalone ticket too.

-----

For now I'm closing the ticket here because it has served its purpose of "let's get a beta package out of the door", the rest ought to be independent tickets & MRs :)

**Comment by kocio-pl** [comment]
> I don't have hamster installed (it's not available in Fedora)

Luckily it's available on Flathub
https://flathub.org/apps/details/org.gnome.Hamster
