### ISSUE TITLE
"Stop Hamster Activity" menu item starts the activity

### ISSUE THREAD

**Issue by LewWadoo** [getting-things-gnome/gtg#80]
The menu item only switches the activity status. When the activity was stopped by Hamster, the menu item still says "Stop Hamster Activity". When the menu item is selected, it actually starts the activity.

**Comment by nekohayo** [comment]
I'm working on putting this project back on its feet with the goal of getting a release out of the door.

This issue here is up for grabs for anyone wanting to see it happen. Please contribute code (or bring in someone who can) to the project for this purpose.

I do not use Hamster myself and orphaned code rarely gets better on its own. If nobody steps forward to maintain it, the code may get deactivated or dropped in the long run.
