### ISSUE TITLE
"Send via e-mail" is indented in the task menu

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#800]
Forked from https://github.com/getting-things-gnome/gtg/issues/793#issuecomment-1046144111

It's a small bug, but still a visible glitch.

**Comment by Neui** [comment]
Didn't knew it appeared there.

Looks similar to #370, except a bit different, since it uses `Gtk.ModelButton` but there isn't an `Gtk.Box` around the label like the Discard (Verwerfen) button does.

![](https://user-images.githubusercontent.com/1196130/154858811-8f4c740c-991b-4bac-b432-8d3094d80bc8.png)
