### ISSUE TITLE
Show emoticons names

### ISSUE THREAD

**Issue by kocio-pl** [getting-things-gnome/gtg#818]
Related to #817

It's hard to properly identify emoticons - they are text-searchable, but we can't see what is their real name. Probably tooltip with a name would be enough?

Here I can only guess what exact name have these icons, we only know that they contain "smiling":

![Zrzut ekranu z 2022-02-26 02-10-34](https://user-images.githubusercontent.com/5439713/155822629-a27c058d-d049-4fe7-a5e1-40ddb9fb65a9.png)

**Comment by nekohayo** [comment]
I'm not sure we have control over that, I'm guessing we're using GTK's standard emoji picker widget, and if it would need tooltips, then that would be a bug to be filed in GTK (if it's not solved in GTK4 already)?

Arguably, the emoji picker is not really meant to teach you about the name of emojis, just to pick emojis; the "gnome-characters" app, on the other hand, gives you the information for each character/symbol/emoji, including the name and the unicode number, because that's its purpose.

**Comment by diegogangl** [comment]
We have no control over the emoji popup since it comes builtin in Gtk, in fact you can open the same popup in any Gtk3 application by pressing `ctrl+.`. I don't know about Gtk4, I think it was a bit more flexible as in you could call it without hacks, but not flexible as in changing the layout.

Closing since it's not something we can do anything about
