### ISSUE TITLE
Why not offer a .deb/.rpm/.AppImage file

### ISSUE THREAD

**Issue by kyon328** [getting-things-gnome/gtg#941]
I really don't wanna install flatpak or snapcraft just for using GTG

**Comment by nekohayo** [comment]
Hi~! RPM, deb, etc. are the downstream distros' responsibility, we don't do those. We release source code, and as a convenience, Flatpak (via Flathub only) because we use it ourselves, it's well-integrated, and it solves a ton of problems (we chose Flatpak naturally, over Snap or AppImage, for numerous reasons that I won't go into here).

Some of this logic is explained [on this wiki page](https://wiki.gnome.org/Apps/GTG/install).

You are welcome to help Fedora and Debian package GTG again (I'd love to see that happen in Fedora particularly, issue #709). I personally have zero time to learn RPM/deb packaging (and if it didn't happen in the last 20 years, I'm confident that me learning this on my free time will pretty much never happen).
