### ISSUE TITLE
Message: Failed to load module "canberra-gtk-module" on start of org.gnome.GTG

### ISSUE THREAD

**Issue by kl-henry** [getting-things-gnome/gtg#954]

**Comment by Neui** [comment]
What is the problem? The `canberra-gtk-module` thing is output by GTK itself because something tells it to load that module, but is otherwise harmless. You can safely ignore that message. The module apparently [plays "event sounds"](https://wiki.archlinux.org/title/Libcanberra)  (probably like clicking on a button does a click sound).

**Comment by nekohayo** [comment]
Indeed it is not caused by us as far as I can tell: `git grep -i canberra` returns nothing from our codebase, and neither does `git grep -i sound`, so something else on the system is causing this, and as long as it's not crashing GTG, it's nothing to worry about.
