### ISSUE TITLE
Font size adjustment for Task List

### ISSUE THREAD

**Issue by genefyx** [getting-things-gnome/gtg#977]
I'm having difficulty viewing the task list on Higher DPI screens. The task editor has font adjustments. Can the task list have this option also? Thank you.

**Comment by nekohayo** [comment]
I don't remember the task editor having adjustable font sizes, simply that the title line gets rendered bigger...

If GTK's rendered UI fonts are too small, until fractional scaling is properly implemented in GNOME, I would suggest you use the "Large Text" accessibility setting, or the "GNOME Tweaks" app to set a different font scale globally, rather than per-application.

**Comment by Neui** [comment]
> I don't remember the task editor having adjustable font sizes

You are (were? I haven't looked in the new release) able to change the font for the task editor, which also includes font size.

**Comment by genefyx** [comment]
Yes, @Neui, the editor was fine, it was just the task list that was being left behind.
@nekohayo The accessibility is a great feature but it causes my web browsing tabs to take up too much room.
So I had to compromise on using per app accessibility features.
I hope the fractional scaling can fix this, I don't know why but I think fedora did things in a way where things are very legible. (Haven't used it in a while to confirm) Maybe that's something I can look into until there's a universal fix. Thank you.
