### ISSUE TITLE
Installation documentation is outdated (Debian/Ubuntu package, Flatpak)

### ISSUE THREAD

**Issue by MagicFab** [getting-things-gnome/gtg#988]
The installation documentation at https://wiki.gnome.org/Apps/GTG/install dates back to 2020, indicating packages availability as of 2019. 

Not sure about other distros but packages for Ubuntu and Debian are available now in:

- Debian 12 / bookworm : [gtg 0.6-2](https://tracker.debian.org/pkg/gtg) (0.6-5 in testing, no backports)
- Ubuntu 23.04 / lunar lobster : [gtg 0.6-2](https://packages.ubuntu.com/lunar/gtg) - universe repository (0.6-5 in Ubuntu 23.10)

The doc also suggests checking releases in Github, the latest is 0.6.
@nekohayo mentioned there is [an official Flatpak](https://flathub.org/apps/org.gnome.GTG) (currently also 0.6), which should be the better/latest option, this isn't mentioned either.

Then it links to the README which only has manual install/build instructions which are also probably oudtated.

**Comment by nekohayo** [comment]
> The installation documentation at https://wiki.gnome.org/Apps/GTG/install dates back to 2020, indicating packages availability as of 2019

Oh yeah, the Ubuntu and Debian packages are very recent apparitions, thanks for providing the links to those packages. I have updated the download information page on the wiki to reflect this.

> Then it links to the README which only has manual install/build instructions which are also probably oudtated.

Other than this dependency having shifted under our feet without us realizing: #984 

... I don't think GTG has changed dependencies much since 2020/2021, but Diego is probably the one who will know best what his new branch requires. I presume the upcoming version (once the mega port to GTK4 is done) will require:
* a very recent version of GTK4 (relying on the presence of many fixes in GTK that happened throughout 2023)
* probably a recent version of pygobject for the same reason
* maybe no liblarch anymore? Does the new core use it at all?
* possibly a recent version of Python, but I don't know which (as we sometimes got surprises with Python deprecations like 3.8 -> 3.9 but it's been a while)...

I think these version numbers would just get bumped accordingly in the readme file and dependencies config files whenever it is needed (probably will need to be done when Diego merges the all_ports branch).

I presume the core of the issue (download wiki page) is complete so I'll close this ticket.
