### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by antrmn** [getting-things-gnome/gtg#994]
GNOME Software shows:

![Screenshot from 2023-12-21 20-48-53](https://github.com/getting-things-gnome/gtg/assets/37816362/a1408758-6cf1-4a0d-9fde-0e3474975e48)

It is a pity for such a featureful piece of software. It seems there's not even a comparable alternative around.

**Comment by SqAtx** [comment]
I wouldn't say that it's abandoned. It's just that it's in a middle of a giant refactor (https://github.com/getting-things-gnome/gtg/pull/894) that (I think) made it difficult for people to get started with the code base. Since a lot of it is about to change, there is no incentive to look at the current code to try and fix existing issues.

If you want to help, please have a look at https://fortintam.com/blog/call-for-testing-gtg-gtk4-branch/

The good news is that the refactor will probably be merged soon. After that, I expect a period of bug fixes before 0.7 can be released with GTK4 etc. Hoping to get more involved myself after the merge.

I think there's hope :)

**Comment by antrmn** [comment]
Awesome! That's relieving to know. I'll try it out ASAP and try to give some feedback if needed. 

Still, I think the GNOME Software message may mislead other people into thinking that all the efforts are redirected onto other apps (like Endeavour, which I genuinely thought was a successor of GTG).

**Comment by nekohayo** [comment]
Yes indeed, we hope to merge the "mega port" branch (#894) mentioned in #737 (see some helpful links there), as soon as we can confirm there are no showstopper problems with it (ideally by February?). You can help test and fix it, and then once it's merged we will need help to fix all the remaining issues.

In https://github.com/getting-things-gnome/gtg/pull/894#issuecomment-1743484451 I have a laundry list of issues I found in this branch, most of them are not showstoppers though.

As for the scary GNOME Software warning: unfortunately that's not something we control. The assumptions flatpak and GNOME Software make do not really match the reality of over-stretched resources-constrained projects that require significant refactoring over long development cycles, which is pretty much the case of any volunteer project needing to port from one major version of GTK to another (if you look even at core GNOME apps, they typically needed 6 to 18 months of work to port from GTK3 to GTK4, some are still not ported…), but in our case we did a core rewrite at the same time, so yeah...
